import { OFFICIAL_FOOTER } from "./invoice-brand";
import { downloadExcel } from "./receipt-export";
import { periodData,periodTotals,periodTitle } from "./statement-period";
import type { StatementPeriod } from "./statement-period";
import { optionalText } from "./client-details";
import { printedAmount as money } from "./invoice-math";
import { balance } from "./client-account";
import { DocumentBackground,DocumentFooter } from "./invoice-paper";
export function accountTotals(invoices:any[],payments:any[],credits:any[]) {return invoices.reduce((a,i)=>{const b=balance(i,payments,credits);return {total:a.total+b.total,received:a.received+b.received,credited:a.credited+b.credited,due:a.due+b.due,refund:a.refund+b.refund};},{total:0,received:0,credited:0,due:0,refund:0});}
export function statementRows(clients:any[],invoices:any[],payments:any[],credits:any[],clientId:string,period:StatementPeriod) {
 if(!clientId)return clients.map(c=>({client:c,...periodTotals(invoices.filter(i=>i.client.id===c.id),payments,credits,period)}));
 const {bills:items,paid,notes}=periodData(invoices.filter(i=>i.client.id===clientId),payments,credits,period);
 const events:any[]=[...items.map(i=>({id:i.id,date:i.date,kind:0,label:"Facture "+i.number,detail:"",debit:balance(i,[],[]).total,credit:0})),...items.filter(i=>i.advance>0).map(i=>({id:"advance-"+i.id,date:i.date,kind:1,label:"Avance · "+i.number,detail:i.payment,debit:0,credit:i.advance})),...notes.map(c=>({id:c.id,date:c.date,kind:2,label:"Avoir "+c.number,detail:c.reason+" · "+c.invoiceNumber,debit:0,credit:c.amount})),...paid.map(p=>({id:p.id,date:p.date,kind:3,label:"Paiement · "+items.find(i=>i.id===p.invoiceId)?.number,detail:[p.method,p.reference].filter(Boolean).join(" · "),debit:0,credit:p.amount}))].sort((a,b)=>a.date.localeCompare(b.date)||a.kind-b.kind||a.id.localeCompare(b.id));
 const before=events.filter(e=>e.date<period.from),opening=before.reduce((n,e)=>n+e.debit-e.credit,0);let running=opening;
 const result=events.filter(e=>e.date>=period.from).map(e=>{running+=e.debit-e.credit;return {...e,running};});
 let reportRunning=0;const reports=items.filter(i=>i.date<period.from).map(i=>{const b=balance(i,paid.filter(p=>p.date<period.from),notes.filter(c=>c.date<period.from));const net=b.total-b.received-b.credited;reportRunning+=net;return{id:"report-"+i.id,date:period.from,label:"Report · Facture "+i.number,detail:"Du "+new Date(i.date+"T12:00:00").toLocaleDateString("fr-FR")+" · Facturé "+money(b.total)+" · Avance "+money(i.advance)+" · Reçu "+money(b.received)+" · Avoirs "+money(b.credited),debit:0,credit:0,running:reportRunning};});
 return before.length?[...reports,{id:"opening",date:period.from,label:"Solde d’ouverture",detail:"Total reporté avant les écritures de la période",debit:0,credit:0,running:opening},...result]:result;
}
export function downloadStatement(clients:any[],invoices:any[],payments:any[],credits:any[],clientId:string,period:StatementPeriod) {
 const rows=statementRows(clients,invoices,payments,credits,clientId,period),header=clientId?["Date","Écriture","Détail","Facturé","Paiement ou avoir","Solde"]:["Client","Facturé","Avoirs","Avances","Reçu","Reste à payer","À restituer"];
 const values=rows.map((r:any)=>clientId?[r.date,r.label,r.detail,r.debit,r.credit,r.running]:[r.client.name,r.total,r.credited,r.advance,r.received,r.due,r.refund]);
 const csv=[[periodTitle(period)],header,...values].map(row=>row.map(v=>{const raw=String(v??"");const safe=typeof v==="string"&&/^[=+\-@\t\r]/.test(raw)?"'"+raw:raw;return '"'+safe.replaceAll('"','""')+'"';}).join(";")).join("\r\n");
 const url=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="situation-"+(clientId?"client":"globale")+"-"+period.from+"-"+period.to+".csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function AccountStatement({clients,invoices,payments,credits,clientId,format,period}:{clients:any[];invoices:any[];payments:any[];credits:any[];clientId:string;format:any;period:StatementPeriod}) {
 const client=clients.find(c=>c.id===clientId),items=client?invoices.filter(i=>i.client.id===clientId):invoices,total=periodTotals(items,payments,credits,period),rows=statementRows(clients,invoices,payments,credits,clientId,period);
 const groups:any[][]=[];let group:any[]=[],height=0;for(const row of rows){const text=client?[row.label,row.detail].join(" "):row.client.name;const h=Math.max(38,18*Math.ceil(text.length/(client?58:28))+16);if(height+h>390&&group.length){groups.push(group);group=[];height=0;}group.push(row);height+=h;}if(group.length||!groups.length)groups.push(group);
 return <div className="document-pages receipt-pages">{groups.map((page,index)=><article key={index} className="document-page receipt-page statement-page" style={{width:794,height:1123}}><DocumentBackground format={format}/><div className="receipt-content">{format.banner&&<img className="receipt-banner" src={format.banner} alt="Bannière"/>}<div className="receipt-title"><h1>{client?"SITUATION DU COMPTE":"SITUATION DES CLIENTS"}</h1></div><div className="statement-identification"><div>{client?<><strong>{client.name}</strong>{[client.address,client.email].some(v=>optionalText(v))&&<p>{[client.address,client.email].map(optionalText).filter(Boolean).join(" · ")}</p>}</>:<strong>Ensemble des clients</strong>}</div><span>{periodTitle(period)}</span></div>{index===0&&<div className="statement-summary"><div><span>Facturé sur la période</span><strong>{money(total.total)}</strong></div><div><span>Avoirs</span><strong>{money(total.credited)}</strong></div><div><span>Reçu sur la période</span><strong>{money(total.received)}</strong></div><div><span>Reste à recevoir</span><strong>{money(total.due)}</strong></div></div>}
 {client?<table className="statement-table"><thead><tr><th>Date</th><th>Écriture</th><th>Facturé</th><th>Paiement ou avoir</th><th>Solde</th></tr></thead><tbody>{page.map((r:any)=><tr key={r.id}><td>{new Date(r.date+"T12:00:00").toLocaleDateString("fr-FR")}</td><td>{r.label}{r.detail&&<small>{r.detail}</small>}</td><td>{r.debit?money(r.debit):"—"}</td><td>{r.credit?money(r.credit):"—"}</td><td>{money(r.running)}</td></tr>)}</tbody></table>:<table className="statement-table statement-global"><thead><tr><th>Client</th><th>Facturé</th><th>Avoirs</th><th>Avances</th><th>Reçu</th><th>Reste à payer</th><th>À restituer</th></tr></thead><tbody>{page.map((r:any)=><tr key={r.client.id}><td>{r.client.name}</td><td>{money(r.total)}</td><td>{money(r.credited)}</td><td>{money(r.advance)}</td><td>{money(r.received)}</td><td>{money(r.due)}</td><td>{money(r.refund)}</td></tr>)}</tbody></table>}
 {!rows.length&&<p>Aucune écriture sur ce compte.</p>}{index===groups.length-1&&<div className="statement-closing">{client&&<p>Solde du compte : <strong>{money(total.closing)}</strong><small>Un solde négatif représente un crédit en faveur du client.</small></p>}{total.refund>0&&<p>À restituer au client : <strong>{money(total.refund)}</strong></p>}<p>Les montants facturés, avoirs et règlements couvrent la période choisie. Le solde inclut les écritures antérieures. Les avances sont comprises dans le reçu.</p><div className="receipt-signature">La Direction.</div></div>}</div><DocumentFooter format={format}/><span className="receipt-page-number">Page {index+1} / {groups.length}</span></article>)}</div>;
}

export function exportStatementExcel(clients:any[],invoices:any[],payments:any[],credits:any[],clientId:string,period:StatementPeriod){
 const rows=statementRows(clients,invoices,payments,credits,clientId,period);
 const header=clientId?["Date","Écriture","Détail","Facturé","Paiement ou avoir","Solde"]:["Client","Facturé (période)","Avoirs (période)","Avances (période)","Reçu (période)","Reste à payer au "+period.to,"À restituer"];
 const values=rows.map((r:any)=>clientId?[r.date,r.label,r.detail,r.debit,r.credit,r.running]:[r.client.name,r.total,r.credited,r.advance,r.received,r.due,r.refund]);
 downloadExcel([[(invoices[0]?.company?.name||"CAPSED SUARL")+" · "+periodTitle(period)],header,...values,[],["La Direction."],["Merci pour votre confiance."],...OFFICIAL_FOOTER.map(line=>[line])],"situation-"+(clientId?"client":"globale")+"-"+period.from+"-"+period.to+".xlsx");
}
