import { optionalText } from "./client-details";
import { formatMoney as money } from "./document-model";
import { balance } from "./client-account";
import { DocumentBackground,DocumentFooter } from "./invoice-paper";
export function accountTotals(invoices:any[],payments:any[],credits:any[]) {return invoices.reduce((a,i)=>{const b=balance(i,payments,credits);return {total:a.total+b.total,received:a.received+b.received,credited:a.credited+b.credited,due:a.due+b.due,refund:a.refund+b.refund};},{total:0,received:0,credited:0,due:0,refund:0});}
export function statementRows(clients:any[],invoices:any[],payments:any[],credits:any[],clientId:string) {
 if(!clientId)return clients.map(c=>({client:c,...accountTotals(invoices.filter(i=>i.client.id===c.id),payments,credits)}));
 const items=invoices.filter(i=>i.client.id===clientId),ids=new Set(items.map(i=>i.id));
 const events:any[]=[...items.map(i=>({id:i.id,date:i.date,kind:0,label:"Facture "+i.number,detail:"",debit:balance(i,[],[]).total,credit:0})),...items.filter(i=>i.advance>0).map(i=>({id:"advance-"+i.id,date:i.date,kind:1,label:"Avance · "+i.number,detail:i.payment,debit:0,credit:i.advance})),...credits.filter(c=>ids.has(c.invoiceId)).map(c=>({id:c.id,date:c.date,kind:2,label:"Avoir "+c.number,detail:c.reason+" · "+c.invoiceNumber,debit:0,credit:c.amount})),...payments.filter(p=>ids.has(p.invoiceId)&&!p.cancelledAt).map(p=>({id:p.id,date:p.date,kind:3,label:"Paiement · "+items.find(i=>i.id===p.invoiceId)?.number,detail:[p.method,p.reference].filter(Boolean).join(" · "),debit:0,credit:p.amount}))].sort((a,b)=>a.date.localeCompare(b.date)||a.kind-b.kind||a.id.localeCompare(b.id));
 let running=0;return events.map(e=>{running+=e.debit-e.credit;return {...e,running};});
}
export function downloadStatement(clients:any[],invoices:any[],payments:any[],credits:any[],clientId:string) {
 const rows=statementRows(clients,invoices,payments,credits,clientId),header=clientId?["Date","Écriture","Détail","Facturé FCFA","Paiement ou avoir FCFA","Solde FCFA"]:["Client","Facturé FCFA","Avoirs FCFA","Reçu FCFA","Reste à payer FCFA","À restituer FCFA"];
 const values=rows.map((r:any)=>clientId?[r.date,r.label,r.detail,r.debit,r.credit,r.running]:[r.client.name,r.total,r.credited,r.received,r.due,r.refund]);
 const csv=[header,...values].map(row=>row.map(v=>{const raw=String(v??"");const safe=typeof v==="string"&&/^[=+\-@\t\r]/.test(raw)?"'"+raw:raw;return '"'+safe.replaceAll('"','""')+'"';}).join(";")).join("\r\n");
 const url=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="situation-"+(clientId?"client":"globale")+"-"+new Date().toISOString().slice(0,10)+".csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function AccountStatement({clients,invoices,payments,credits,clientId,format}:{clients:any[];invoices:any[];payments:any[];credits:any[];clientId:string;format:any}) {
 const client=clients.find(c=>c.id===clientId),items=client?invoices.filter(i=>i.client.id===clientId):invoices,total=accountTotals(items,payments,credits),rows=statementRows(clients,invoices,payments,credits,clientId);
 const groups:any[][]=[];let group:any[]=[],height=0;for(const row of rows){const text=client?[row.label,row.detail].join(" "):row.client.name;const h=Math.max(38,18*Math.ceil(text.length/(client?58:28))+16);if(height+h>480&&group.length){groups.push(group);group=[];height=0;}group.push(row);height+=h;}if(group.length||!groups.length)groups.push(group);
 return <div className="document-pages receipt-pages">{groups.map((page,index)=><article key={index} className="document-page receipt-page statement-page" style={{width:794,height:1123}}><DocumentBackground format={format}/><div className="receipt-content">{format.banner&&<img className="receipt-banner" src={format.banner} alt="Bannière"/>}<div className="receipt-title"><h1>{client?"SITUATION DU COMPTE":"SITUATION DES CLIENTS"}</h1></div><div className="statement-identification"><div>{client?<><strong>{client.name}</strong>{[client.address,client.email].some(v=>optionalText(v))&&<p>{[client.address,client.email].map(optionalText).filter(Boolean).join(" · ")}</p>}</>:<strong>Ensemble des clients · toutes les factures</strong>}</div><span>État au {new Date().toLocaleDateString("fr-FR")}</span></div>{index===0&&<div className="statement-summary"><div><span>Total facturé</span><strong>{money(total.total)}</strong></div><div><span>Avoirs</span><strong>{money(total.credited)}</strong></div><div><span>Reçu</span><strong>{money(total.received)}</strong></div><div><span>Reste à recevoir</span><strong>{money(total.due)}</strong></div></div>}
 {client?<table className="statement-table"><thead><tr><th>Date</th><th>Écriture</th><th>Facturé</th><th>Paiement ou avoir</th><th>Solde</th></tr></thead><tbody>{page.map((r:any)=><tr key={r.id}><td>{new Date(r.date+"T12:00:00").toLocaleDateString("fr-FR")}</td><td>{r.label}{r.detail&&<small>{r.detail}</small>}</td><td>{r.debit?money(r.debit):"—"}</td><td>{r.credit?money(r.credit):"—"}</td><td>{money(r.running)}</td></tr>)}</tbody></table>:<table className="statement-table statement-global"><thead><tr><th>Client</th><th>Facturé</th><th>Avoirs</th><th>Reçu</th><th>Reste à payer</th><th>À restituer</th></tr></thead><tbody>{page.map((r:any)=><tr key={r.client.id}><td>{r.client.name}</td><td>{money(r.total)}</td><td>{money(r.credited)}</td><td>{money(r.received)}</td><td>{money(r.due)}</td><td>{money(r.refund)}</td></tr>)}</tbody></table>}
 {!rows.length&&<p>Aucune écriture sur ce compte.</p>}{index===groups.length-1&&<div className="statement-closing">{client&&<p>Solde du compte : <strong>{money(total.total-total.credited-total.received)}</strong><small>Un solde négatif représente un crédit en faveur du client.</small></p>}{total.refund>0&&<p>À restituer au client : <strong>{money(total.refund)}</strong></p>}<p>Les avances sont comprises dans les paiements reçus. Les paiements annulés sont exclus.</p><div className="receipt-signature">La Direction</div></div>}</div><DocumentFooter format={format}/><span className="receipt-page-number">Page {index+1} / {groups.length}</span></article>)}</div>;
}
