import { useState } from "react";
import { ArrowRight, Bell, Check, Clock3, FileText, LockKeyhole, RefreshCw, Search, Send, WifiOff } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { balance } from "./client-account";
import { formatMoney as money } from "./document-model";

export type ControlRequest = {
  id: string; clientId: string; clientName: string; invoiceId: string; invoiceNumber: string;
  amount: number; paymentDate: string; method: string; reference: string; message: string;
  createdAt: string; receivedAt?: string; readAt?: string; resolvedAt?: string; response?: string;
};
export type ControlSnapshot = { clients: any[]; invoices: any[]; payments: any[]; credits: any[]; deliveries: {invoiceId:string;declaredAt:string}[]; receivedAt: string };
const methods = ["Banque", "Espèces", "MTN Mobile Money", "Orange Money"];
const localDate = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
const when = (date: string) => new Date(date).toLocaleString("fr-FR", { day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit" });
function RequestStatus({ request: r }: { request: ControlRequest }) {
  return <span className={`request-status ${r.resolvedAt ? "done" : r.readAt ? "read" : "waiting"}`}>{r.resolvedAt ? <Check size={12}/> : <Clock3 size={12}/>} {r.resolvedAt ? "Traitée" : r.readAt ? "Lue" : r.receivedAt ? "Reçue sur le poste" : "En attente de connexion"}</span>;
}
export function SimulationNotice() { return <div className="control-simulation"><span>SIMULATION</span> Aucun poste distant connecté. Les demandes d’essai restent dans cette session.</div>; }

export function ControlCenter({ snapshot, requests, connected, onSend, onSync, onConnection, onLock }: {
  snapshot: ControlSnapshot; requests: ControlRequest[]; connected: boolean;
  onLock: (id:string) => void; onSend: (r: ControlRequest) => void; onSync: () => void; onConnection: () => void;
}) {
  const [search,setSearch] = useState(""), [clientId,setClientId] = useState("");
  const [compose,setCompose] = useState(false), [invoiceId,setInvoiceId] = useState("");
  const [amount,setAmount] = useState(""), [date,setDate] = useState(localDate()), [method,setMethod] = useState(methods[0]);
  const [reference,setReference] = useState(""), [message,setMessage] = useState(""), [error,setError] = useState("");
  const clients = snapshot.clients.filter(c => (c.name+" "+c.phone).toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr")));
  const client = clients.find(c => c.id === clientId) ?? clients[0];
  const items = client ? snapshot.invoices.filter(i => i.client.id === client.id).sort((a,b) => b.date.localeCompare(a.date)) : [];
  const totals = (invoices: any[]) => invoices.reduce((a,i) => { const b = balance(i,snapshot.payments,snapshot.credits); return {due:a.due+b.due,received:a.received+b.received,total:a.total+b.total}; },{due:0,received:0,total:0});
  const all = totals(snapshot.invoices), account = totals(items);
  function startRequest() { setInvoiceId(items.find(i => balance(i,snapshot.payments,snapshot.credits).due > 0)?.id ?? items[0]?.id ?? ""); setAmount(""); setDate(localDate()); setMethod(methods[0]); setReference(""); setMessage(""); setError(""); setCompose(true); }
  function send() {
    const invoice = items.find(i => i.id === invoiceId), value = Number(amount);
    if (!client || !invoice) return setError("Choisissez la facture concernée.");
    if (!Number.isSafeInteger(value) || value <= 0) return setError("Saisissez un montant entier positif.");
    if (!date) return setError("Indiquez la date du paiement.");
    onSend({id:crypto.randomUUID(),clientId:client.id,clientName:client.name,invoiceId:invoice.id,invoiceNumber:invoice.number,amount:value,paymentDate:date,method,reference:reference.trim(),message:message.trim(),createdAt:new Date().toISOString()}); setCompose(false);
  }
  return <><div className="heading"><div><h1>Contrôle de l’activité</h1></div><button className="outline" onClick={onSync} disabled={!connected}><RefreshCw size={15}/> Simuler une synchronisation</button></div><SimulationNotice/>
    <div className={`sync-health ${connected ? "connected" : "disconnected"}`}><span className="sync-health-icon">{connected ? <Check size={18}/> : <WifiOff size={18}/>}</span><div><strong>{connected ? "Poste disponible dans la simulation" : "Poste de facturation hors ligne · simulation"}</strong><p>{connected ? "La connexion seule ne met pas à jour les données. Lancez la synchronisation." : "Un paiement peut avoir été saisi sur le poste sans apparaître ici."}</p></div><div className="sync-health-time"><span>Dernière synchronisation simulée</span><strong>{when(snapshot.receivedAt)}</strong></div><button className="text-action" onClick={onConnection}>{connected ? "Simuler une coupure" : "Simuler la reconnexion"}</button></div>
    <div className="desktop-account-metrics control-metrics"><div><span>Reste à recevoir · état connu</span><strong>{money(all.due)}</strong></div><div><span>Paiements connus</span><strong>{money(all.received)}</strong></div><div><span>Demandes à traiter</span><strong>{requests.filter(r => !r.resolvedAt).length}</strong></div></div>
    <div className="control-grid"><section className="card control-clients"><div className="register-list-header"><h2>Clients</h2><label className="register-search"><Search size={15}/><input aria-label="Chercher un client dans le contrôle" placeholder="Chercher un client…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{clients.map(c=>{const a=totals(snapshot.invoices.filter(i=>i.client.id===c.id));return <button key={c.id} className={`control-client-row ${client?.id===c.id ? "selected" : ""}`} onClick={()=>setClientId(c.id)}><span><strong>{c.name}</strong><small>{snapshot.invoices.filter(i=>i.client.id===c.id).length} facture(s)</small></span><span><strong>{money(a.due)}</strong><small>{a.due ? "À recevoir" : "Aucun solde"}</small></span><ArrowRight size={15}/></button>})}{!clients.length && <div className="empty">Aucun client trouvé.</div>}</section>
    <section className="card control-client-detail">{client ? <><div className="control-detail-heading"><div><h2>{client.name}</h2><span>État reçu le {when(snapshot.receivedAt)}</span></div><button className="primary" onClick={startRequest} disabled={!items.length}><Send size={15}/> Demander une vérification</button></div><div className="control-client-balance"><span>Reste à recevoir</span><strong>{money(account.due)}</strong><span className="freshness-label">{connected ? "Selon la dernière synchronisation" : "Données à confirmer"}</span></div><div className="table-wrap"><table className="control-invoices"><thead><tr><th>Facture</th><th>Reçu</th><th>Reste à payer</th><th>État connu</th><th>Document</th></tr></thead><tbody>{items.map(i=>{const b=balance(i,snapshot.payments,snapshot.credits);return <tr key={i.id}><td><FileText size={14}/>{i.number}</td><td>{money(b.received)}</td><td>{money(b.due)}</td><td><span className={`payment-status ${b.due ? "unpaid":"paid"}`}>{b.status}</span></td><td><span className="document-delivery-state">{snapshot.deliveries.some(d=>d.invoiceId===i.id) ? "Remise déclarée" : "Remise non confirmée"}</span></td></tr>})}</tbody></table>{!items.length && <div className="empty">Aucune facture reçue pour ce client.</div>}</div><div className="list-head"><h2>Paiements connus</h2></div>{snapshot.payments.filter(p=>!p.cancelledAt && items.some(i=>i.id===p.invoiceId)).map(p=><div className="request-history" key={p.id}><div><strong>{money(p.amount)} · {p.method}</strong><small>{p.date} · {items.find(i=>i.id===p.invoiceId)?.number}{p.reference ? " · "+p.reference : ""}</small></div>{p.lockedAt ? <span className="payment-lock-badge"><LockKeyhole size={12}/> Validé · verrouillé</span> : <button className="outline" disabled={!connected} title={!connected ? "Reconnectez le poste simulé avant validation" : "Valider ce paiement et empêcher son annulation"} onClick={()=>onLock(p.id)}><LockKeyhole size={13}/> Valider et verrouiller</button>}</div>)}{!snapshot.payments.some(p=>!p.cancelledAt && items.some(i=>i.id===p.invoiceId)) && <p className="control-no-requests">Aucun versement distinct connu. Les avances sont incluses dans les factures.</p>}<div className="control-delivery-note">Une remise déclarée par l’équipe ne confirme pas la réception par le client.</div><div className="list-head"><h2>Demandes de vérification</h2></div>{requests.filter(r=>r.clientId===client.id).map(r=><div className="request-history" key={r.id}><div><strong>{money(r.amount)} · {r.invoiceNumber}</strong><small>{when(r.createdAt)} · {r.method}</small>{r.response && <p>{r.response}</p>}</div><RequestStatus request={r}/></div>)}{!requests.some(r=>r.clientId===client.id) && <p className="control-no-requests">Aucune demande pour ce client.</p>}</> : <div className="empty">Choisissez un client.</div>}</section></div>
    <Dialog open={compose} onOpenChange={setCompose}><DialogContent className="payment-dialog"><DialogHeader><DialogTitle>Demander une vérification</DialogTitle><DialogDescription>{client?.name} · demande d’essai, aucun envoi réel</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();send();}}><div className="grid-fields"><label className="field control-wide"><span>Facture</span><select value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}>{items.map(i=><option key={i.id} value={i.id}>{i.number}</option>)}</select></label><label className="field"><span>Montant reçu (FCFA)</span><input required type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Ex. 50 000"/></label><label className="field"><span>Date du paiement</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>Mode de paiement</span><select value={method} onChange={e=>setMethod(e.target.value)}>{methods.map(m=><option key={m}>{m}</option>)}</select></label><label className="field"><span>Référence · facultatif</span><input value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="field control-wide"><span>Message · facultatif</span><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ex. Paiement reçu ce matin, à vérifier."/></label></div><p className="credit-form-note">Cette demande ne modifie pas le solde. L’équipe vérifie avant d’enregistrer le paiement.</p>{error && <p className="payment-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="outline" onClick={()=>setCompose(false)}>Annuler</button><button type="submit" className="primary"><Send size={15}/> Créer la demande d’essai</button></div></form></DialogContent></Dialog>
  </>;
}

export function TeamNotifications({requests,connected,onSync,onConnection,onRead,onResolve,onInvoice,onPayment,payments,invoices,credits}: {
  requests:ControlRequest[];connected:boolean;onSync:()=>void;onConnection:()=>void;onRead:(id:string)=>void;onResolve:(id:string,response:string)=>void;
  onInvoice:(id:string)=>void;onPayment:(id:string)=>void;payments:any[];invoices:any[];credits:any[];
}) {
  const [selected,setSelected]=useState(""),[response,setResponse]=useState(""),[filter,setFilter]=useState<"open"|"done">("open");
  const received=requests.filter(r=>r.receivedAt),pending=requests.filter(r=>!r.receivedAt);
  const visible=received.filter(r=>filter==="done" ? !!r.resolvedAt : !r.resolvedAt);
  const active=received.find(r=>r.id===selected);
  function open(r:ControlRequest){setSelected(r.id);setResponse(r.response??"");onRead(r.id);}
  return <><div className="heading"><div><h1>Notifications</h1></div><button className="outline" onClick={connected ? onSync : onConnection}><RefreshCw size={15}/> {connected ? "Simuler une synchronisation" : "Simuler la reconnexion"}</button></div><SimulationNotice/>{!connected && <div className="notification-waiting"><WifiOff size={16}/><span>Poste hors ligne dans la simulation. Les nouvelles demandes attendent la reconnexion.</span></div>}{pending.length>0 && <div className="notification-waiting"><WifiOff size={16}/><span>{pending.length} demande(s) en attente de réception dans la simulation.</span></div>}
    <div className="register-tabs" role="tablist" aria-label="Notifications"><button role="tab" aria-selected={filter==="open"} onClick={()=>setFilter("open")}>À traiter <span>{received.filter(r=>!r.resolvedAt).length}</span></button><button role="tab" aria-selected={filter==="done"} onClick={()=>setFilter("done")}>Traitées <span>{received.filter(r=>r.resolvedAt).length}</span></button></div>
    <section className="card notification-list">{visible.map(r=><button className={`notification-row ${!r.readAt ? "unread":""}`} key={r.id} onClick={()=>open(r)}><span className="notification-symbol"><Bell size={18}/></span><span><strong>{r.clientName}</strong><p>Paiement à vérifier · {money(r.amount)} · {r.invoiceNumber}</p><small>{when(r.receivedAt!)}{r.readAt ? "":" · Non lue"}</small></span><RequestStatus request={r}/><ArrowRight size={16}/></button>)}{!visible.length && <div className="empty"><Bell size={26}/><strong>{filter==="done" ? "Aucune demande traitée":"Aucune notification reçue"}</strong><span>{pending.length ? connected ? "Synchronisez pour recevoir les demandes d’essai." : "Simulez la reconnexion, puis synchronisez." : "Les demandes du responsable apparaîtront ici après synchronisation."}</span></div>}</section>
    <Dialog open={!!active} onOpenChange={open=>{if(!open)setSelected("");}}><DialogContent className="notification-dialog"><DialogHeader><DialogTitle>Paiement à vérifier</DialogTitle><DialogDescription>{active?.clientName} · {active?.invoiceNumber}</DialogDescription></DialogHeader>{active && <><div className="notification-request-amount"><strong>{money(active.amount)}</strong><span>{active.paymentDate} · {active.method}</span>{active.reference && <span>Référence : {active.reference}</span>}</div>{active.message && <p className="notification-message">{active.message}</p>}<div className="notification-context-actions"><button className="outline" disabled={!invoices.some(i=>i.id===active.invoiceId)} onClick={()=>{setSelected("");onInvoice(active.invoiceId);}}>Voir la facture</button><button className="primary" disabled={!invoices.some(i=>i.id===active.invoiceId && balance(i,payments,credits).due>0)} onClick={()=>{setSelected("");onPayment(active.invoiceId);}}>Vérifier / enregistrer le paiement</button></div>{payments.some(p=>p.invoiceId===active.invoiceId && !p.cancelledAt && p.amount===active.amount) && <p className="notification-match">Un paiement du même montant existe déjà. Vérifiez sa date et sa référence avant toute nouvelle saisie.</p>}<RequestStatus request={active}/>{active.resolvedAt ? <p className="notification-message">{active.response}</p> : <form onSubmit={e=>{e.preventDefault();if(response.trim()){onResolve(active.id,response.trim());setSelected("");}}}><label className="field"><span>Résultat de la vérification</span><input required value={response} onChange={e=>setResponse(e.target.value)} placeholder="Ex. Déjà enregistré, référence OM123."/></label><p className="credit-form-note">Traiter la demande ne crée pas de paiement. Le solde change uniquement lors d’une écriture de paiement.</p><div className="dialog-actions"><button type="submit" className="primary" disabled={!response.trim()}><Check size={15}/> Marquer comme traitée</button></div></form>}</>}</DialogContent></Dialog>
  </>;
}
