import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Clock3, LockKeyhole, RefreshCw, Search, Send, WifiOff } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { balance } from "./client-account";
import { formatMoney as money } from "./document-model";
import { RequestStatus } from "./control-center";
import type { ControlRequest, ControlSnapshot } from "./control-center";

const methods=["Banque","Espèces","MTN Mobile Money","Orange Money"];
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;};
const when=(s:string)=>new Date(s).toLocaleString("fr-FR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"});
export default function ControlCenter({snapshot,requests,connected,onSend,onSync,onConnection,onLock}:{snapshot:ControlSnapshot;requests:ControlRequest[];connected:boolean;onSend:(r:ControlRequest)=>void;onSync:()=>void;onConnection:()=>void;onLock:(id:string)=>void}){
  const region=useRef<HTMLDivElement>(null);
  const [search,setSearch]=useState(""),[clientId,setClientId]=useState("");
  const [compose,setCompose]=useState(false),[invoiceId,setInvoiceId]=useState("");
  const [amount,setAmount]=useState(""),[date,setDate]=useState(localDate()),[method,setMethod]=useState(methods[0]),[reference,setReference]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
  useEffect(()=>{const scroll=region.current?.closest(".content");if(scroll)scroll.scrollTop=0;window.scrollTo({top:0,behavior:"auto"});},[clientId]);
  const client=snapshot.clients.find(c=>c.id===clientId);
  const items=client?snapshot.invoices.filter(i=>i.client.id===client.id).sort((a,b)=>b.date.localeCompare(a.date)):[];
  const knownPayments=snapshot.payments.filter(p=>!p.cancelledAt&&items.some(i=>i.id===p.invoiceId));
  const clientRequests=requests.filter(r=>r.clientId===clientId);
  const total=(invoices:any[])=>invoices.reduce((a,i)=>{const b=balance(i,snapshot.payments,snapshot.credits);return {due:a.due+b.due,received:a.received+b.received,refund:a.refund+b.refund};},{due:0,received:0,refund:0});
  const account=total(items);
  function startRequest(id?:string){setInvoiceId(id??items.find(i=>balance(i,snapshot.payments,snapshot.credits).due>0)?.id??items[0]?.id??"");setAmount("");setDate(localDate());setMethod(methods[0]);setReference("");setMessage("");setError("");setCompose(true);}
  function send(){const invoice=items.find(i=>i.id===invoiceId),value=Number(amount);if(!client||!invoice)return setError("Choisissez une facture.");if(!Number.isSafeInteger(value)||value<=0)return setError("Indiquez un montant entier positif.");if(!date)return setError("Indiquez la date du paiement.");onSend({id:crypto.randomUUID(),clientId:client.id,clientName:client.name,invoiceId:invoice.id,invoiceNumber:invoice.number,amount:value,paymentDate:date,method,reference:reference.trim(),message:message.trim(),createdAt:new Date().toISOString()});setCompose(false);}
  return <div className="mobile-control-flow" ref={region}>
    {client ? <><button className="control-back" onClick={()=>setClientId("")}><ArrowLeft size={18}/> Tous les clients</button><div className="heading"><h1>{client.name}</h1></div></> : <div className="heading"><h1>Suivi des clients</h1><span className="control-prototype-label">Simulation</span></div>}
    <div className="control-freshness"><span>{connected?<Clock3 size={15}/>:<WifiOff size={15}/>} État reçu le {when(snapshot.receivedAt)}</span>{!connected&&<small>Poste hors ligne · des saisies peuvent manquer.</small>}</div>
    {!client ? <><label className="control-find"><Search size={18}/><input aria-label="Chercher un client dans le contrôle" placeholder="Chercher un client" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="control-client-cards">{snapshot.clients.filter(c=>(c.name+" "+c.phone).toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr"))).map(c=>{const invoices=snapshot.invoices.filter(i=>i.client.id===c.id),a=total(invoices),pending=requests.filter(r=>r.clientId===c.id&&!r.resolvedAt).length;return <button className="control-client-card" key={c.id} onClick={()=>{setClientId(c.id);}}><div><strong>{c.name}</strong><ArrowRight size={18}/></div><div><span className={`client-state ${a.due ? "due":"clear"}`}>{!invoices.length?"Aucune facture":a.refund?"À restituer":!a.due?"Soldé":a.received?"Paiement partiel":"À payer"}</span><strong className="client-card-amount">{money(a.due||a.refund)}</strong></div>{pending>0&&<small>{pending} demande{pending>1?"s":""} en cours</small>}</button>})}{!snapshot.clients.some(c=>(c.name+" "+c.phone).toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr")))&&<div className="empty">Aucun client trouvé.</div>}</div></> : <>
      <section className="control-simple-balance"><span>Reste à recevoir · état connu</span><strong>{money(account.due)}</strong>{account.refund>0&&<p>À restituer : {money(account.refund)}</p>}<button className="primary" onClick={()=>startRequest()} disabled={!items.length}><Send size={17}/> Signaler un paiement</button></section>
      <section className="control-simple-section"><h2>Factures <span>{items.length}</span></h2><div className="control-invoice-cards">{items.map(i=>{const b=balance(i,snapshot.payments,snapshot.credits),delivered=snapshot.deliveries.some(d=>d.invoiceId===i.id);return <details className="control-invoice-card" key={i.id}><summary><span><strong>{i.number}</strong><small>{b.status}</small></span><span><strong>{money(b.due)}</strong><small>reste à payer</small></span></summary><div className="control-invoice-extra"><div><span>Total</span><strong>{money(b.total)}</strong></div><div><span>Reçu</span><strong>{money(b.received)}</strong></div>{b.credited>0&&<div><span>Avoirs</span><strong>{money(b.credited)}</strong></div>}<p>{delivered?"Remise déclarée par l’équipe":"Remise au client non confirmée"}</p><button className="outline" onClick={()=>startRequest(i.id)}>Signaler un paiement</button></div></details>})}</div>{!items.length&&<p className="control-section-empty">Aucune facture connue.</p>}</section>
      <section className="control-simple-section"><h2>Paiements <span>{knownPayments.length}</span></h2>{knownPayments.map(p=><div className="control-payment-card" key={p.id}><div><strong>{money(p.amount)}</strong><span>{p.method} · {p.date}</span>{p.reference&&<small>{p.reference}</small>}</div>{p.lockedAt?<span className="payment-lock-badge"><LockKeyhole size={12}/> Validé</span>:<button className="outline" disabled={!connected} title={!connected?"Reconnectez le poste simulé pour valider":"Valider et verrouiller ce paiement"} onClick={()=>onLock(p.id)}><LockKeyhole size={14}/> Valider</button>}</div>)}{!knownPayments.length&&<p className="control-section-empty">Aucun versement distinct. Les avances figurent sur les factures.</p>}</section>
      {clientRequests.length>0&&<section className="control-simple-section"><h2>Demandes <span>{clientRequests.length}</span></h2>{clientRequests.map(r=><details className="control-request-card" key={r.id}><summary><strong>{money(r.amount)}</strong><RequestStatus request={r}/></summary><div><p>{r.invoiceNumber} · {r.method}</p>{r.message&&<p>{r.message}</p>}{r.response&&<p><strong>Réponse :</strong> {r.response}</p>}</div></details>)}</section>}
    </>}
    <details className="control-demo-tools"><summary>Connexion et essai</summary><p>Échanges simulés, sans poste distant. Les demandes et verrous d’essai disparaissent au rechargement.</p><div><button className="outline" onClick={onConnection}>{connected?"Simuler une coupure":"Simuler la reconnexion"}</button><button className="outline" onClick={onSync} disabled={!connected}><RefreshCw size={15}/> Synchroniser l’essai</button></div></details>
    <Dialog open={compose} onOpenChange={setCompose}><DialogContent className="payment-dialog control-request-dialog"><DialogHeader><DialogTitle>Signaler un paiement</DialogTitle><DialogDescription>{client?.name} · demande d’essai à l’équipe</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();send();}}><div className="grid-fields"><label className="field control-wide"><span>Facture</span><select value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}>{items.map(i=><option key={i.id} value={i.id}>{i.number}</option>)}</select></label><label className="field"><span>Montant reçu (FCFA)</span><input required type="number" inputMode="numeric" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Ex. 50 000"/></label><label className="field"><span>Date du paiement</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field control-wide"><span>Mode de paiement</span><select value={method} onChange={e=>setMethod(e.target.value)}>{methods.map(m=><option key={m}>{m}</option>)}</select></label></div><details className="line-options"><summary>Référence ou message · facultatif</summary><div className="grid-fields"><label className="field"><span>Référence</span><input value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="field"><span>Message</span><input value={message} onChange={e=>setMessage(e.target.value)}/></label></div></details><p className="credit-form-note">L’équipe vérifie la demande avant d’enregistrer le paiement.</p>{error&&<p className="payment-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="outline" onClick={()=>setCompose(false)}>Annuler</button><button type="submit" className="primary"><Send size={15}/> Envoyer la demande d’essai</button></div></form></DialogContent></Dialog>
  </div>;
}
