import { clientDetailLines } from "./client-details";
import { formatMoney as money } from "./document-model";
import type { CreditArticle,TaxMode } from "./invoice-math";
import { quantityLabel } from "./invoice-math";
import { DocumentBackground,DocumentFooter } from "./invoice-paper";
export type CreditNote={id:string;invoiceId:string;number:string;date:string;amount:number;ht:number;tax:number;taxRate:number;taxMode?:TaxMode;lines?:CreditArticle[];reason:string;invoiceNumber:string;invoiceDate:string;client:any;company:any;format:{banner:string;footerText:string;footerImage:string;stationery?:string|false}};
export default function CreditPaper({credit:c}:{credit:CreditNote}) {
 const taxable=c.taxMode?c.taxMode==="ttc":c.taxRate>0,rows=c.lines?.length?c.lines:[{sourceLineId:"amount",designation:c.reason,destination:"",quantity:1,unitPrice:c.ht,ht:c.ht,tax:c.tax,amount:c.amount}];
 const groups:any[][]=[[]];let height=0;for(const row of rows){const estimate=Math.max(42,Math.ceil(row.designation.length/40)*17,row.designation.split("\n").length*17)+12;if(height+estimate>380&&groups.at(-1)!.length){groups.push([]);height=0;}groups.at(-1)!.push(row);height+=estimate;}
 return <div className="document-pages receipt-pages">{groups.map((group,index)=><article key={index} className="document-page receipt-page" style={{width:794,height:1123}}><DocumentBackground format={c.format}/><div className="receipt-content">{c.format.banner&&<img className="receipt-banner" src={c.format.banner} alt="Bannière"/>}<div className="receipt-title"><h1>FACTURE D’AVOIR</h1><span>{index>0?"Suite":""}</span></div><div className="receipt-info"><div><small>FACTURÉ À</small><strong>{c.client.name}</strong>{clientDetailLines(c.client).map((text,index)=><p key={index}>{text}</p>)}</div><div className="receipt-reference"><strong>{c.number}</strong><p>{new Date(c.date+"T12:00:00").toLocaleDateString("fr-FR")}</p><p>Facture concernée : <strong>{c.invoiceNumber}</strong></p><p>du {new Date(c.invoiceDate+"T12:00:00").toLocaleDateString("fr-FR")}</p></div></div><p className="credit-motif"><strong>Motif de l’avoir :</strong> {c.reason}</p><table className="receipt-table credit-items-table"><thead><tr><th>Articles concernés</th><th>Quantité</th><th>Montant HT déduit</th>{taxable&&<th>TVA</th>}<th>Montant déduit</th></tr></thead><tbody>{group.map((l:any)=><tr key={l.sourceLineId}><td>{l.designation}{l.destination&&<small>{l.destination}</small>}</td><td>{quantityLabel(l.quantity)}</td><td>{money(l.ht)}</td>{taxable&&<td>{money(l.tax)}</td>}<td>{money(l.amount)}</td></tr>)}</tbody></table>{index===groups.length-1&&<><div className="receipt-totals"><p><span>Montant HT de l’avoir</span><strong>{money(c.ht)}</strong></p>{taxable&&<p><span>TVA ({c.taxRate} %)</span><strong>{money(c.tax)}</strong></p>}<p className="receipt-total"><span>Total déduit</span><strong>{money(c.amount)}</strong></p></div><p className="field-note">Cet avoir réduit le montant de la facture {c.invoiceNumber}. Il ne constitue pas un paiement.</p><div className="receipt-signature">La Direction</div></>}</div><DocumentFooter format={c.format}/>{groups.length>1&&<span className="receipt-page-number">Page {index+1} / {groups.length}</span>}</article>)}</div>;
}
