import { optionalText } from "./client-details";
import { Plus, Trash2, FileText, ArrowRight } from "lucide-react";
import { NativeSelect } from "@/components/ui/native-select";
import { invoiceTotals, lineAmount, paymentMethods } from "./invoice-math";
import type { TaxMode } from "./invoice-math";
import { formatMoney as money } from "./document-model";
export type InvoiceDraft = { clientId:string; date:string; lines:any[]; taxRate:number; taxMode:TaxMode; discountRate:number; advance:number; payment:string; note:string; purchaseOrder:string };
export default function InvoiceComposer({draft,onChange,clients,onClient,onEditClient,onSave,error,number}:{draft:InvoiceDraft;onChange:(patch:Partial<InvoiceDraft>)=>void;clients:any[];onClient:()=>void;onEditClient:()=>void;onSave:()=>void;error:string;number?:string}) {
 const totals=invoiceTotals(draft), client=clients.find(c=>c.id===draft.clientId);
 const update=(id:string,patch:any)=>onChange({lines:draft.lines.map(l=>l.id===id?{...l,...patch}:l)});
 return <><div className="heading"><h1>{number ? "Modifier "+number : "Créer une facture"}</h1></div><div className="compose"><div className="compose-body">
 <section className="card form-card"><div className="form-title"><b>1</b><h2>Client et facture</h2></div><div className="select-row"><label className="field"><span>Client *</span><NativeSelect value={draft.clientId} onChange={e=>onChange({clientId:e.target.value})}><option value="">Choisir un client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</NativeSelect></label><button className="outline" onClick={onClient}><Plus size={17}/> Nouveau client</button></div>{client&&<div className="chosen"><span className="initial">{client.name[0]}</span><div><strong>{client.name}</strong>{optionalText(client.address)&&<span>{client.address}</span>}</div><button type="button" className="client-details-edit" onClick={onEditClient}>Modifier les coordonnées</button></div>}
 <p className="field-note">Vous pouvez choisir une date d’un mois précédent pour saisir une ancienne facture. Les mois clôturés restent protégés.</p><div className="grid-fields invoice-identification"><label className="field"><span>Date de facture</span><input type="date" value={draft.date} onChange={e=>onChange({date:e.target.value})}/></label><label className="field"><span>Numéro de bon de commande <small>facultatif</small></span><input value={draft.purchaseOrder} onChange={e=>onChange({purchaseOrder:e.target.value})} placeholder="Ex. BC-2026-014"/></label></div>
 <fieldset className="tax-mode-choice"><legend>Type de facture</legend>{([["ht","Facture hors taxe"],["ttc","Facture TTC"]] as const).map(([value,label])=><label key={value} className={draft.taxMode===value?"selected":""}><input type="radio" name="taxMode" value={value} checked={draft.taxMode===value} onChange={()=>onChange({taxMode:value})}/>{label}</label>)}</fieldset>{draft.taxMode==="ttc"&&<p className="field-note">Les prix sont saisis hors taxe. La TVA s’ajoute après la remise.</p>}</section>
 <section className="card form-card">{draft.lines.some(l=>!Number.isInteger(l.quantity))&&<p className="payment-error">Cette ancienne facture contient une quantité décimale. Choisissez une quantité entière avant d’enregistrer ; le montant sera recalculé et l’ancienne version conservée.</p>}<div className="form-title"><b>2</b><h2>Articles et prestations</h2></div>{draft.lines.map((l,index)=><div className="line-item" key={l.id}><div className="line-title"><strong>Article {index+1}</strong>{draft.lines.length>1&&<button onClick={()=>onChange({lines:draft.lines.filter(x=>x.id!==l.id)})}><Trash2 size={16}/> Retirer</button>}</div><div className="grid-fields"><label className="field"><span>Désignation *</span><textarea rows={4} value={l.designation} placeholder={"Traitement phytosanitaire\nConteneur MSNU 923173-6\nConteneur TRHU 411783-8"} onChange={e=>update(l.id,{designation:e.target.value})}/></label><label className="field"><span>Destination <small>facultatif</small></span><textarea rows={4} value={l.destination} placeholder={"Kolkata\nNorfolk"} onChange={e=>update(l.id,{destination:e.target.value})}/></label><label className="field"><span>Quantité</span><input type="number" inputMode="numeric" min="1" step="1" value={l.quantity} onChange={e=>update(l.id,{quantity:Number(e.target.value)})}/></label><label className="field"><span>Prix unitaire hors taxe (FCFA)</span><input type="number" min="0" step="1" value={l.unitPrice} onChange={e=>update(l.id,{unitPrice:Number(e.target.value)})}/></label></div>{l.contract&&<label className="field"><span>Référence de contrat existante</span><input value={l.contract} onChange={e=>update(l.id,{contract:e.target.value})}/></label>}<div className="line-subtotal"><span>Montant de l’article</span><strong>{money(lineAmount(l))}</strong></div></div>)}<button className="add-line" onClick={()=>onChange({lines:[...draft.lines,{id:crypto.randomUUID(),contract:"",designation:"",destination:"",quantity:1,unitPrice:0}]})}><Plus size={18}/> Ajouter un article</button></section>
 <section className="card form-card"><div className="form-title"><b>3</b><h2>Remise et règlement</h2></div><div className="grid-fields"><label className="field"><span>Remise (%)</span><input type="number" min="0" max="100" step="any" value={draft.discountRate} onChange={e=>onChange({discountRate:Number(e.target.value)})}/></label>{draft.taxMode==="ttc"&&<label className="field"><span>TVA (%)</span><input type="number" min="0" max="100" step="any" value={draft.taxRate} onChange={e=>onChange({taxRate:Number(e.target.value)})}/></label>}<label className="field"><span>Avance versée à la facturation (FCFA)</span><input type="number" min="0" step="1" value={draft.advance} onChange={e=>onChange({advance:Number(e.target.value)})}/></label><label className="field"><span>Mode de règlement</span><NativeSelect value={draft.payment} onChange={e=>onChange({payment:e.target.value})}>{!paymentMethods.includes(draft.payment)&&<option value={draft.payment}>{draft.payment} · ancien mode</option>}{paymentMethods.map(m=><option key={m}>{m}</option>)}</NativeSelect></label><label className="field wide"><span>Note facultative</span><textarea rows={2} value={draft.note} onChange={e=>onChange({note:e.target.value})}/></label></div></section>
 </div><aside className="summary"><div className="card"><h2>Total</h2>{totals.discount>0&&<><p><span>Montant de départ</span><strong>{money(totals.subtotal)}</strong></p><p><span>Remise ({draft.discountRate} %)</span><strong>− {money(totals.discount)}</strong></p></>}<p><span>{totals.discount>0?"Montant HT après remise":"Montant HT"}</span><strong>{money(totals.ht)}</strong></p>{draft.taxMode==="ttc"&&<><p><span>TVA ({draft.taxRate} %)</span><strong>{money(totals.tax)}</strong></p><p><span>Total TTC</span><strong>{money(totals.ttc)}</strong></p></>}{draft.advance>0&&<p><span>Avance reçue</span><strong>− {money(draft.advance)}</strong></p>}<div><span>{draft.advance>0?"Reste à payer":totals.totalLabel}</span><strong>{money(totals.due)}</strong></div>{number&&<p className="field-note">Le numéro reste identique. La version précédente est conservée.</p>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary" onClick={onSave}>{number?"Enregistrer les modifications":"Émettre la facture"}<ArrowRight size={18}/></button></div></aside></div></>;
}
