import { useState } from "react";
import { Search, CalendarDays, Plus, ArrowRight, FileText, LockKeyhole, Undo2, Check } from "lucide-react";
import { balance, PaymentStatus } from "./client-account";
import type { Payment } from "./client-account";
import type { CreditNote } from "./credit-note";
import { formatMoney as money } from "./document-model";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";

type RegisterInvoice = { id: string; number: string; date: string; client: { id: string; name: string }; lines: { quantity: number; unitPrice: number }[]; advance: number; payment: string; taxRate: number };
const date = (s: string) => new Date(s + "T12:00:00").toLocaleDateString("fr-FR", { day: "2-digit", month: "short", year: "numeric" });
const periodLabel = (s: string) => new Date(s + "-01T12:00:00").toLocaleDateString("fr-FR", { month: "long", year: "numeric" });
export default function InvoiceRegister({ invoices, payments, credits, month, onMonth, tab, onTab, closed, onClose, onNew, onInvoice, onCredit, onCreateCredit, onPayment, onClient, onEdit }: {
  invoices: RegisterInvoice[]; payments: Payment[]; credits: CreditNote[]; month: string; onMonth: (month: string) => void;
  tab: "factures" | "avoirs"; onTab: (tab: "factures" | "avoirs") => void; closed: boolean; onClose: () => void; onNew: () => void;
  onInvoice: (id: string) => void; onCredit: (id: string) => void; onCreateCredit: (id: string) => void;
  onEdit: (id: string) => void; onPayment: (id: string) => void; onClient: (id: string) => void;
}) {
  const [search, setSearch] = useState(""), [choosing, setChoosing] = useState(false), [pickerSearch, setPickerSearch] = useState("");
  const [selected, setSelected] = useState("");
  const bills = invoices.filter(i => i.date.startsWith(month)).sort((a,b) => b.number.localeCompare(a.number));
  const notes = credits.filter(c => c.date.startsWith(month)).sort((a,b) => b.number.localeCompare(a.number));
  const matches = (text: string) => text.toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr"));
  const shownBills = bills.filter(i => matches(i.number + " " + i.client.name));
  const shownNotes = notes.filter(c => matches(c.number + " " + c.client.name + " " + c.invoiceNumber));
  const eligible = invoices.filter(i => { const b = balance(i, payments, credits); return b.credited < b.total; }).sort((a,b) => b.date.localeCompare(a.date));
  const amount = tab === "factures" ? bills.reduce((s,i) => s + balance(i,payments,credits).due, 0) : notes.reduce((s,c) => s + c.amount, 0);
  const activeBill = shownBills.find(i => i.id === selected) ?? shownBills[0];
  const activeNote = shownNotes.find(c => c.id === selected) ?? shownNotes[0];
  const activeBalance = activeBill ? balance(activeBill, payments, credits) : null;
  function selectTab(next: "factures" | "avoirs") { onTab(next); setSearch(""); }
  return <>
    <div className="heading"><div><h1>Factures & avoirs</h1></div>{tab === "factures" ? <button className="primary" onClick={onNew} disabled={closed}><Plus size={18} /> Nouvelle facture</button> : <button className="primary" onClick={() => { setPickerSearch(""); setChoosing(true); }} disabled={!eligible.length}><Plus size={18} /> Créer un avoir</button>}</div>
    <div className="register-period-row"><label><CalendarDays size={18} /><span>Mois</span><input type="month" value={month} aria-label="Choisir le mois" onChange={e => { if (e.target.value) onMonth(e.target.value); }} /></label><span className={closed ? "period-state closed" : "period-state"}>{closed ? <LockKeyhole size={13} /> : <Check size={13} />}{closed ? "Mois clôturé" : "Mois ouvert"}</span></div>
    <div className="register-tabs" role="tablist" aria-label="Documents du mois"><button role="tab" id="invoice-tab" aria-controls="invoice-register-panel" aria-selected={tab === "factures"} tabIndex={tab === "factures" ? 0 : -1} onClick={() => selectTab("factures")} onKeyDown={e => { if (e.key === "ArrowRight" || e.key === "ArrowLeft") { e.preventDefault(); selectTab("avoirs"); document.getElementById("credit-tab")?.focus(); } }}><FileText size={19} /> Factures <span>{bills.length}</span></button><button role="tab" id="credit-tab" aria-controls="invoice-register-panel" aria-selected={tab === "avoirs"} tabIndex={tab === "avoirs" ? 0 : -1} onClick={() => selectTab("avoirs")} onKeyDown={e => { if (e.key === "ArrowRight" || e.key === "ArrowLeft") { e.preventDefault(); selectTab("factures"); document.getElementById("invoice-tab")?.focus(); } }}><Undo2 size={19} /> Avoirs <span>{notes.length}</span></button></div>
    <section className="register-workspace" id="invoice-register-panel" role="tabpanel" aria-labelledby={tab === "factures" ? "invoice-tab" : "credit-tab"}>
      <div className="register-metrics"><div><span>{tab === "factures" ? "Facturé" : "Montant des avoirs"}</span><strong>{money(tab === "factures" ? bills.reduce((s,i) => s + balance(i,payments,credits).total,0) : amount)}</strong></div><div><span>{tab === "factures" ? "Paiements reçus" : "Documents émis"}</span><strong>{tab === "factures" ? money(bills.reduce((s,i) => s + balance(i,payments,credits).received,0)) : notes.length}</strong></div><div className="metric-accent"><span>{tab === "factures" ? "Reste à recevoir" : "Factures concernées"}</span><strong>{tab === "factures" ? money(amount) : new Set(notes.map(n => n.invoiceId)).size}</strong></div></div><div className="register-split">
      <section className="card register-records"><div className="register-list-header"><div><h2>{tab === "factures" ? "Factures" : "Avoirs"} de {periodLabel(month)}</h2><p>{tab === "factures" ? "Sélectionnez une ligne pour consulter les détails." : "Chaque avoir est lié à une facture et réduit son montant."}</p></div><label className="register-search"><Search size={17} /><input placeholder={tab === "factures" ? "Chercher une facture…" : "Chercher un avoir…"} aria-label={tab === "factures" ? "Rechercher une facture" : "Rechercher un avoir"} value={search} onChange={e => setSearch(e.target.value)} /></label></div>
      {tab === "factures" && shownBills.length > 0 && <><div className="table-wrap register-desktop"><table className="invoice-list"><thead><tr><th>Numéro</th><th>Client</th><th>Date</th><th>Montant</th><th>Statut</th><th><span className="sr-only">Ouvrir</span></th></tr></thead><tbody>{shownBills.map(i => <tr key={i.id} className={activeBill?.id === i.id ? "selected-record" : ""} aria-selected={activeBill?.id === i.id} tabIndex={0} onClick={() => setSelected(i.id)} onDoubleClick={() => onInvoice(i.id)} onKeyDown={e => { if(e.key === "Enter") onInvoice(i.id); }}><td><span className="doc-icon"><FileText size={18} /></span><strong>{i.number}</strong></td><td><strong>{i.client.name}</strong></td><td>{date(i.date)}</td><td className="numeric-cell">{money(balance(i,payments,credits).total)}</td><td><PaymentStatus invoice={i} payments={payments} credits={credits} /></td><td><button className="record-open" aria-label={"Ouvrir la facture " + i.number} onClick={e => { e.stopPropagation(); onInvoice(i.id); }}><ArrowRight size={16} /></button></td></tr>)}</tbody></table></div><div className="register-mobile">{shownBills.map(i => <button className="register-mobile-record" key={i.id} onClick={() => onInvoice(i.id)}><div><strong>{i.client.name}</strong><span>{money(balance(i,payments,credits).total)}</span></div><div><small>{i.number} · {date(i.date)}</small><ArrowRight size={16} /></div><PaymentStatus invoice={i} payments={payments} credits={credits} /></button>)}</div></>}
      {tab === "avoirs" && shownNotes.length > 0 && <><div className="table-wrap register-desktop"><table className="register-credit-table"><thead><tr><th>Avoir</th><th>Client</th><th>Facture d’origine</th><th>Date</th><th>Montant</th><th><span className="sr-only">Ouvrir</span></th></tr></thead><tbody>{shownNotes.map(c => <tr key={c.id} className={activeNote?.id === c.id ? "selected-record" : ""} aria-selected={activeNote?.id === c.id} tabIndex={0} onClick={() => setSelected(c.id)} onDoubleClick={() => onCredit(c.id)} onKeyDown={e => { if(e.key === "Enter") onCredit(c.id); }}><td><strong>{c.number}</strong></td><td>{c.client.name}</td><td>{c.invoiceNumber}</td><td>{date(c.date)}</td><td className="numeric-cell">− {money(c.amount)}</td><td><button className="record-open" aria-label={"Ouvrir l’avoir " + c.number} onClick={e => { e.stopPropagation(); onCredit(c.id); }}><ArrowRight size={16} /></button></td></tr>)}</tbody></table></div><div className="register-mobile">{shownNotes.map(c => <button className="register-mobile-record" key={c.id} onClick={() => onCredit(c.id)}><div><strong>{c.client.name}</strong><span>− {money(c.amount)}</span></div><div><small>{c.number} · {date(c.date)}</small><ArrowRight size={16} /></div><p>Facture d’origine : {c.invoiceNumber}</p></button>)}</div></>}
      {(tab === "factures" ? !shownBills.length : !shownNotes.length) && <div className="register-empty">{tab === "factures" ? <FileText size={30} /> : <Undo2 size={30} />}<h3>{search ? "Aucun résultat" : tab === "factures" ? "Pas encore de facture ce mois-ci" : "Pas encore d’avoir ce mois-ci"}</h3><p>{search ? "Essayez le nom du client ou le numéro du document." : tab === "factures" ? "Créez votre première facture pour cette période." : "Un avoir sert à réduire ou annuler le montant d’une facture existante."}</p>{!search && (tab === "factures" ? <button className="primary" onClick={onNew} disabled={closed}>Créer une facture</button> : <button className="outline" onClick={() => { setPickerSearch(""); setChoosing(true); }} disabled={!eligible.length}>Choisir la facture concernée</button>)}</div>}
      <div className="list-foot"><span>{tab === "factures" ? bills.length + (bills.length === 1 ? " facture" : " factures") : notes.length + (notes.length === 1 ? " avoir" : " avoirs")} · {periodLabel(month)}</span><button onClick={onClose} disabled={closed}><LockKeyhole size={16} />{closed ? "Mois clôturé" : "Clôturer ce mois"}</button></div></section>
      <aside className="document-inspector" aria-label="Détails du document sélectionné">
        <div className="inspector-heading"><span>Détails</span><FileText size={16} /></div>
        {tab === "factures" && activeBill && activeBalance ? <><div className="inspector-identity"><span className="inspector-document-icon"><FileText size={24} /></span><h2>{activeBill.number}</h2><PaymentStatus invoice={activeBill} payments={payments} credits={credits} /></div><div className="inspector-section"><span>Client</span><button className="inspector-client" onClick={() => onClient(activeBill.client.id)}>{activeBill.client.name}<ArrowRight size={14} /></button><dl><div><dt>Date</dt><dd>{date(activeBill.date)}</dd></div><div><dt>Prestations</dt><dd>{activeBill.lines.length}</dd></div><div><dt>Règlement</dt><dd>{activeBill.payment}</dd></div></dl></div><div className="inspector-section"><dl><div><dt>Total facturé</dt><dd>{money(activeBalance.total)}</dd></div><div><dt>Reçu</dt><dd>{money(activeBalance.received)}</dd></div>{activeBalance.credited > 0 && <div><dt>Avoirs</dt><dd>− {money(activeBalance.credited)}</dd></div>}</dl><div className="inspector-balance"><span>Reste à payer</span><strong>{money(activeBalance.due)}</strong></div>{activeBalance.refund > 0 && <p className="inspector-refund">À restituer : {money(activeBalance.refund)}</p>}</div><div className="inspector-actions"><button className="primary" onClick={() => onInvoice(activeBill.id)}><FileText size={16} /> Ouvrir la facture</button><button className="outline" disabled={closed} onClick={()=>onEdit(activeBill.id)}>Modifier la facture</button>{activeBalance.due > 0 && <button className="outline" onClick={() => onPayment(activeBill.id)}>Enregistrer un paiement</button>}{activeBalance.credited < activeBalance.total && <button className="text-action" onClick={() => onCreateCredit(activeBill.id)}><Undo2 size={14} /> Créer un avoir</button>}</div></> : tab === "avoirs" && activeNote ? <><div className="inspector-identity"><span className="inspector-document-icon"><Undo2 size={24} /></span><h2>{activeNote.number}</h2><span className="credit-caption">Facture d’avoir</span></div><div className="inspector-section"><span>Client</span><button className="inspector-client" onClick={() => onClient(activeNote.client.id)}>{activeNote.client.name}<ArrowRight size={14} /></button><dl><div><dt>Date</dt><dd>{date(activeNote.date)}</dd></div><div><dt>Facture d’origine</dt><dd>{activeNote.invoiceNumber}</dd></div></dl></div><div className="inspector-section"><span>Motif</span><p>{activeNote.reason}</p><div className="inspector-balance"><span>Montant de l’avoir</span><strong>− {money(activeNote.amount)}</strong></div></div><div className="inspector-actions"><button className="primary" onClick={() => onCredit(activeNote.id)}>Ouvrir l’avoir</button><button className="outline" onClick={() => onInvoice(activeNote.invoiceId)}>Voir la facture d’origine</button></div></> : <div className="inspector-placeholder"><FileText size={28} /><p>Aucun document sélectionné.</p></div>}
      </aside></div>
    </section>
    <Dialog open={choosing} onOpenChange={setChoosing}><DialogContent className="credit-picker-dialog"><DialogHeader><DialogTitle>Quelle facture voulez-vous corriger ?</DialogTitle><DialogDescription>Choisissez la facture d’origine.</DialogDescription></DialogHeader><label className="register-search"><Search size={17} /><input autoFocus aria-label="Chercher la facture d’origine" placeholder="Nom du client ou numéro…" value={pickerSearch} onChange={e => setPickerSearch(e.target.value)} /></label><div className="credit-picker-list">{eligible.filter(i => (i.number + " " + i.client.name).toLocaleLowerCase("fr").includes(pickerSearch.toLocaleLowerCase("fr"))).map(i => <button key={i.id} onClick={() => { setChoosing(false); onCreateCredit(i.id); }}><span><strong>{i.client.name}</strong><small>{i.number} · {date(i.date)}</small></span><span><strong>{money(balance(i,payments,credits).total - balance(i,payments,credits).credited)}</strong><small>Montant encore facturé</small></span><ArrowRight size={17} /></button>)}</div>{!eligible.some(i => (i.number + " " + i.client.name).toLocaleLowerCase("fr").includes(pickerSearch.toLocaleLowerCase("fr"))) && <p className="picker-no-results">Aucune facture trouvée. Essayez un autre nom ou numéro.</p>}</DialogContent></Dialog>
  </>;
}
