import { OFFICIAL_FOOTER } from "./invoice-brand";
import { clientDetailLines, optionalText } from "./client-details";
import { useLayoutEffect, useRef, useState } from "react";
import { invoiceTotals, lineAmount, printedQuantity, quantityLabel, normalizePayment } from "./invoice-math";
import { printedAmount as money } from "./invoice-math";
export const CAPSED_STATIONERY="capsed-letterhead.webp";
export function DocumentBackground({format}:{format:any}) {return <img className="receipt-stationery" src={CAPSED_STATIONERY} alt=""/>;}
export function DocumentFooter({format}:{format:any}) {return <footer className="receipt-official-footer"><p className="receipt-thanks">Merci pour votre confiance.</p><div className="receipt-legal-footer">{OFFICIAL_FOOTER.map((line,index)=><p key={index}>{line}</p>)}</div></footer>;}
export function modelFormat(model:any) {return {stationery:model.stationery??CAPSED_STATIONERY,banner:model.blocks?.find((b:any)=>b.kind==="image"&&b.y<200)?.image||"",footerText:model.blocks?.find((b:any)=>b.kind==="footer")?.text?.startsWith("Pied de page provisoire")?"":model.blocks?.find((b:any)=>b.kind==="footer")?.text?.trim()||"",footerImage:model.blocks?.find((b:any)=>b.kind==="image"&&b.y>1000)?.image||""};}
function Lines({lines,invoice}:{lines:any[];invoice:any}) {return <table className="receipt-table"><thead><tr><th>Désignation</th><th>Destination</th><th>Quantité</th><th>P. U.</th><th>Montant HT</th></tr></thead><tbody>{lines.map(l=><tr key={l.id}><td>{l.designation}{l.contract&&<small>Contrat : {l.contract}</small>}</td><td>{l.destination}</td><td>{Number.isInteger(l.quantity)?printedQuantity(l.quantity):quantityLabel(l.quantity)}</td><td>{money(l.unitPrice)}</td><td>{money(lineAmount(l))}</td></tr>)}</tbody></table>;}
export default function InvoicePaper({model,invoice:i,words}:{model:any;invoice:any;words:(n:number)=>string}) {
 const t=invoiceTotals(i),format=modelFormat(model),measure=useRef<HTMLDivElement>(null),[heights,setHeights]=useState<number[]>([]);
 useLayoutEffect(()=>{const rows=measure.current?.querySelectorAll("tbody tr");if(rows){const next=Array.from(rows).map(r=>(r as HTMLElement).offsetHeight);setHeights(old=>JSON.stringify(old)===JSON.stringify(next)?old:next);}},[i.lines]);
 const capacity=t.discount>0&&i.advance>0?235:t.taxMode==="ttc"||t.discount>0?270:320;
 const groups:any[][]=[[]];let used=0;
 i.lines.forEach((line:any,index:number)=>{const h=heights[index]??Math.max(45,20+Math.max(line.designation.split("\n").length,(line.destination||"").split("\n").length)*17);if(used+h>capacity&&groups.at(-1)!.length){groups.push([]);used=0;}groups.at(-1)!.push(line);used+=h;});
 return <div className="document-pages receipt-pages"><div className="document-measurement receipt-measurement" ref={measure}><Lines lines={i.lines} invoice={i}/></div>{groups.map((rows,index)=><article className="document-page receipt-page" key={index} aria-label={"Facture "+i.number+", page "+(index+1)} style={{width:794,height:1123}}><DocumentBackground format={format}/><div className="receipt-content">{format.banner&&<img className="receipt-banner" src={format.banner} alt="Bannière"/>}{!format.stationery&&!format.banner&&<div className="receipt-company"><strong>{i.company.name}</strong><p>{i.company.subtitle}</p></div>}<div className="receipt-title"><h1>FACTURE</h1><span>{index>0?"Suite · ":""}{t.taxMode==="ttc"?"TTC":"Hors taxe"}</span></div><div className="receipt-info"><div><small>FACTURÉ À</small><strong>{i.client.name}</strong>{clientDetailLines(i.client).map((text:string,n:number)=><p key={n}>{text}</p>)}</div><div className="receipt-reference"><div><small>N° FACTURE</small><strong>{i.number}</strong></div><div><small>DATE</small><strong>{new Date(i.date+"T12:00:00").toLocaleDateString("fr-FR")}</strong></div><p>Référence : {i.number}</p>{i.purchaseOrder?.trim()&&<p><strong>B C N° :</strong> {i.purchaseOrder}</p>}</div></div><Lines lines={rows} invoice={i}/>{index===groups.length-1&&<><div className="receipt-totals">{t.discount>0&&<><p><span>Montant de départ</span><strong>{money(t.subtotal)}</strong></p><p><span>Remise</span><strong>− {money(t.discount)}</strong></p></>}<p><span>{t.discount>0?"Montant HT après remise":"Montant HT"}</span><strong>{money(t.ht)}</strong></p>{t.taxMode==="ttc"&&<><p><span>TVA</span><strong>{money(t.tax)}</strong></p><p className="receipt-total"><span>Total TTC</span><strong>{money(t.ttc)}</strong></p></>}{i.advance>0&&<><p><span>Avance reçue</span><strong>− {money(i.advance)}</strong></p><p className="receipt-total"><span>Reste à payer</span><strong>{money(t.due)}</strong></p></>}</div><p className="receipt-words">Arrêtée la présente facture à la somme de <strong>{words(t.ttc).toUpperCase()} FRANCS CFA.</strong></p><div className="receipt-payment">{optionalText(i.note)&&<p className="receipt-note">{i.note}</p>}<p><u>Mode de règlement :</u> {normalizePayment(i.payment)}</p><div className="receipt-signature">La Direction.</div></div></>}</div><DocumentFooter format={format}/>{groups.length>1&&<span className="receipt-page-number">Page {index+1} / {groups.length}</span>}</article>)}</div>;
}
