"use client";

import { useEffect, useState } from "react";
import type { CSSProperties } from "react";
import { ArrowLeft, ArrowRight, Building2, CalendarDays, Check, CircleHelp, Download, FilePlus2, FileText, FolderOpen, LayoutTemplate, LockKeyhole, Menu, Pencil, Plus, Printer, Search, ShieldCheck, Trash2, Users, X, PanelLeftClose, PanelLeftOpen, Bell, Activity } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { NativeSelect } from "@/components/ui/native-select";
import InvoiceRegister from "./invoice-register";
import DocumentPreview from "./document-preview";
import WorkspaceHelp from "./workspace-help";
import { TeamNotifications } from "./control-center";
import ControlCenter from "./control-mobile";
import type { ControlRequest, ControlSnapshot } from "./control-center";
import ClientAccount, { balance, PaymentStatus } from "./client-account";
import type { Payment } from "./client-account";
import FormatSettings, { defaultFormat, restoreFormat, fixedModel } from "./invoice-format";
import type { InvoiceFormat } from "./invoice-format";
import type { DocumentModel } from "./document-model";
import CreditPaper from "./credit-note";
import type { CreditNote } from "./credit-note";
import { DocumentPages } from "./document-renderer";
import { invoiceTotals, paymentMethods, normalizePayment, creditSelection } from "./invoice-math";
import type { TaxMode } from "./invoice-math";
import InvoiceComposer from "./invoice-composer";
import type { InvoiceDraft } from "./invoice-composer";
import CreditComposer from "./credit-composer";
import AccountStatement, { downloadStatement } from "./account-statement";
import { modelFormat } from "./invoice-paper";

type Client = { id: string; name: string; contact: string; address: string; phone: string; email: string; niu: string; rc: string };
type Company = { name: string; subtitle: string; address: string; phone: string; email: string; niu: string; rc: string; website: string; logo: string };
type Line = { id: string; contract: string; designation: string; destination: string; quantity: number; unitPrice: number };
type InvoiceTemplate = { banner: string; heading: string; paymentLabel: string; footer: string; layout: "classic" | "compact" | "banner"; accent: string; document?: DocumentModel };
type Invoice = { id: string; number: string; date: string; client: Client; company: Company; lines: Line[]; taxRate: number; advance: number; payment: string; note: string; taxMode?: TaxMode; discountRate?: number; purchaseOrder?: string; revisedAt?: string; history?: any[]; template?: InvoiceTemplate };
type View = "factures" | "clients" | "suivi" | "entreprise" | "modele" | "creation" | "apercu" | "avoir" | "controle" | "notifications" | "situation";
const initialCompany: Company = { name: "CAPSED SUARL", subtitle: "Société camerounaise de prestation et de services divers", address: "B.P. 3463 Douala, Cameroun", phone: "+237 243 55 31 56 / 674 55 73 73 / 699 92 80 02", email: "capsedsarl@gmail.com", niu: "M021612485549 S", rc: "RC/DLA/2016B599", website: "", logo: "" };
const initialTemplate: InvoiceTemplate = { banner: "", heading: "FACTURE", paymentLabel: "MODE DE RÈGLEMENT", footer: "Merci pour votre confiance.", layout: "classic", accent: "#1d5573" };
const initialClients: Client[] = [
  { id: "c1", name: "EFMK SARL", contact: "", address: "BP 23247 Douala · 107 Rue Dominique Savio", phone: "+237 4 23 45 67", email: "comptabilite@efmk.cm", niu: "M04000018203-U", rc: "RC/DLN/2008/B/2325" },
  { id: "c2", name: "Horizon Distribution", contact: "Mme Claire M.", address: "Bonapriso, Douala", phone: "+237 6 77 34 58 12", email: "finance@horizon.cm", niu: "M09221188991P", rc: "RC/DLA/2020/B/451" },
  { id: "c3", name: "Atlas Commerce", contact: "M. Alain T.", address: "Akwa, Douala", phone: "+237 6 95 42 07 31", email: "admin@atlas.cm", niu: "M08001123917L", rc: "RC/DLA/2018/B/238" },
];
const initialInvoices: Invoice[] = [
  { id: "i1", number: "2026-09-001", date: "2026-09-08", client: initialClients[0], company: initialCompany, lines: [{ id: "l1", contract: "CTE1207111", designation: "23 colis Matandze", destination: "Likous", quantity: 37.803, unitPrice: 2500 }], taxRate: 19.25, advance: 0, payment: "Chèque", note: "" },
  { id: "i2", number: "2026-09-002", date: "2026-09-17", client: initialClients[1], company: initialCompany, lines: [{ id: "l2", contract: "CTE1207112", designation: "Prestation de livraison", destination: "Douala", quantity: 2, unitPrice: 45000 }], taxRate: 19.25, advance: 25000, payment: "Espèces", note: "" },
];
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; };
const emptyClient = (): Client => ({ id: "", name: "", contact: "", address: "", phone: "", email: "", niu: "", rc: "" });
const emptyLine = (): Line => ({ id: crypto.randomUUID(), contract: "", designation: "", destination: "", quantity: 1, unitPrice: 0 });
const money = (n: number) => `${new Intl.NumberFormat("fr-FR", { maximumFractionDigits: 0 }).format(Math.round(n))} FCFA`;
const dateLabel = (s: string) => new Intl.DateTimeFormat("fr-FR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date(`${s}T12:00:00`));
const monthLabel = (s: string) => new Intl.DateTimeFormat("fr-FR", { month: "long", year: "numeric" }).format(new Date(`${s}-01T12:00:00`));
function words(n: number): string {
  n = Math.round(n); if (!n) return "zéro";
  const u = ["", "un", "deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf", "dix", "onze", "douze", "treize", "quatorze", "quinze", "seize", "dix-sept", "dix-huit", "dix-neuf"];
  const below100 = (v: number): string => { if (v < 20) return u[v]; if (v < 70) { const d = Math.floor(v / 10), r = v % 10; return ["", "", "vingt", "trente", "quarante", "cinquante", "soixante"][d] + (r === 1 ? " et un" : r ? "-" + u[r] : ""); } if (v < 80) return v === 71 ? "soixante et onze" : "soixante-" + below100(v - 60); return "quatre-vingt" + (v === 80 ? "s" : "-" + below100(v - 80)); };
  const below1000 = (v: number): string => v < 100 ? below100(v) : (Math.floor(v / 100) === 1 ? "cent" : u[Math.floor(v / 100)] + " cent" + (v % 100 ? "" : "s")) + (v % 100 ? " " + below100(v % 100) : "");
  if (n >= 1e9) return new Intl.NumberFormat("fr-FR").format(n);
  const parts: string[] = []; const m = Math.floor(n / 1e6), k = Math.floor((n % 1e6) / 1000), r = n % 1000;
  if (m) parts.push(m === 1 ? "un million" : below1000(m) + " millions"); if (k) parts.push(k === 1 ? "mille" : below1000(k).replace(/cents$/, "cent") + " mille"); if (r) parts.push(below1000(r)); return parts.join(" ");
}
function Paper({ invoice }: { invoice: Invoice }) { return <DocumentPages model={invoice.template?.document ?? fixedModel(defaultFormat)} invoice={invoice} words={words}/>; }
export default function Home() {
  const [registerTab, setRegisterTab] = useState<"factures" | "avoirs">("factures");
  const [payments, setPayments] = useState<Payment[]>([]);
  const [accountClientId, setAccountClientId] = useState("");
  const [paymentInvoiceId, setPaymentInvoiceId] = useState("");
  const [paymentAmount, setPaymentAmount] = useState("");
  const [paymentDate, setPaymentDate] = useState(today());
  const [paymentMethod, setPaymentMethod] = useState("Espèces");
  const [paymentReference, setPaymentReference] = useState("");
  const [paymentError, setPaymentError] = useState("");
  const [cancelPaymentId, setCancelPaymentId] = useState("");
  const [format, setFormat] = useState<InvoiceFormat>(defaultFormat);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [credits, setCredits] = useState<CreditNote[]>([]);
  const [selectedCreditId, setSelectedCreditId] = useState("");
  const [creditInvoiceId, setCreditInvoiceId] = useState("");
  const [creditAmount, setCreditAmount] = useState("");
  const [creditReason, setCreditReason] = useState("");
  const [creditDate, setCreditDate] = useState(today());
  const [creditError, setCreditError] = useState("");
  const [creditMode,setCreditMode]=useState<"articles"|"amount">("articles");
  const [creditQuantities,setCreditQuantities]=useState<Record<string,number>>({});
  const [editingId,setEditingId]=useState("");
  const [draftTaxMode,setDraftTaxMode]=useState<TaxMode>("ht");
  const [draftDiscount,setDraftDiscount]=useState(0);
  const [draftPurchaseOrder,setDraftPurchaseOrder]=useState("");
  const [statementClientId,setStatementClientId]=useState("");
  const [view, setView] = useState<View>("factures"), [clients, setClients] = useState(initialClients), [company, setCompany] = useState(initialCompany), [template, setTemplate] = useState<InvoiceTemplate>(initialTemplate), [invoices, setInvoices] = useState(initialInvoices);
  const [month, setMonth] = useState("2026-09"), [closedMonths, setClosedMonths] = useState<string[]>([]), [selectedId, setSelectedId] = useState("i1"), [search, setSearch] = useState("");
  const [clientDialog, setClientDialog] = useState(false), [clientForm, setClientForm] = useState<Client>(emptyClient()), [closeDialog, setCloseDialog] = useState(false), [mobileMenu, setMobileMenu] = useState(false);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [controlSnapshot, setControlSnapshot] = useState<ControlSnapshot | null>(null);
  const [controlRequests, setControlRequests] = useState<ControlRequest[]>([]);
  const [teamRequests, setTeamRequests] = useState<ControlRequest[]>([]);
  const [teamLockedPaymentIds, setTeamLockedPaymentIds] = useState<string[]>([]);
  const [invoiceDeliveries, setInvoiceDeliveries] = useState<{invoiceId:string;declaredAt:string}[]>([]);
  const [controlConnected, setControlConnected] = useState(false);
  const [notice, setNotice] = useState(""), [loaded, setLoaded] = useState(false), [formError, setFormError] = useState("");
  const [draftClientId, setDraftClientId] = useState(""), [draftDate, setDraftDate] = useState("2026-09-29"), [draftLines, setDraftLines] = useState<Line[]>([emptyLine()]), [draftTax, setDraftTax] = useState(19.25), [draftAdvance, setDraftAdvance] = useState(0), [draftPayment, setDraftPayment] = useState("Espèces"), [draftNote, setDraftNote] = useState("");
  useEffect(() => { try { const raw = localStorage.getItem("capsed-facture-v1"); if (raw) { const d = JSON.parse(raw); setClients(d.clients ?? initialClients); setCompany(d.company ?? initialCompany); setTemplate(d.template ?? initialTemplate); setFormat(restoreFormat(d)); setCredits(d.credits ?? []); setSidebarCollapsed(!!d.sidebarCollapsed); setInvoices(d.invoices ?? initialInvoices); setPayments(d.payments ?? []); setClosedMonths(d.closedMonths ?? []); if (d.month) setMonth(d.month); } } catch {} setLoaded(true); }, []);
  useEffect(() => { if (loaded) { try { localStorage.setItem("capsed-facture-v1", JSON.stringify({ clients, company, template, invoices, closedMonths, format, month, payments, credits, sidebarCollapsed })); } catch { setNotice("Stockage plein : exportez vos données ou réduisez vos images."); } } }, [loaded, clients, company, template, invoices, closedMonths, format, month, payments, credits, sidebarCollapsed]);
  useEffect(() => { if (loaded && !controlSnapshot) setControlSnapshot(structuredClone({clients,invoices,payments,credits,deliveries:invoiceDeliveries,receivedAt:new Date(Date.now()-2*60*60*1000).toISOString()})); }, [loaded,controlSnapshot,clients,invoices,payments,credits,invoiceDeliveries]);
  function lockControlPayment(id:string) { if(!controlConnected || !controlSnapshot) return; const known=controlSnapshot.payments.find(p=>p.id===id),local=payments.find(p=>p.id===id); if(!known || known.cancelledAt || !local || local.cancelledAt || local.amount!==known.amount || local.date!==known.date || local.method!==known.method || local.reference!==known.reference) return setNotice("Synchronisez les données avant de valider ce paiement."); const stamp=new Date().toISOString(); setControlSnapshot(s=>s?{...s,payments:s.payments.map(p=>p.id===id?{...p,lockedAt:stamp}:p)}:s); setTeamLockedPaymentIds(ids=>ids.includes(id)?ids:[...ids,id]); setNotice("Paiement validé et verrouillage reçu sur le poste simulé."); }
  function simulateSync() { if (!controlConnected) return; const stamp = new Date().toISOString(); const merged = controlRequests.map(r=>{ const local=teamRequests.find(t=>t.id===r.id); return {...r,receivedAt:r.receivedAt??stamp,readAt:local?.readAt??r.readAt,resolvedAt:local?.resolvedAt??r.resolvedAt,response:local?.response??r.response}; }); setControlSnapshot(structuredClone({clients,invoices,payments:payments.map(p=>teamLockedPaymentIds.includes(p.id)?{...p,lockedAt:controlSnapshot?.payments.find(k=>k.id===p.id)?.lockedAt??stamp}:p),credits,deliveries:invoiceDeliveries,receivedAt:stamp})); setControlRequests(merged); setTeamRequests(structuredClone(merged)); setNotice("Synchronisation simulée : données, demandes et réponses actualisées."); }
  useEffect(() => { if (notice) { const id = window.setTimeout(() => setNotice(""), 4500); return () => window.clearTimeout(id); } }, [notice]);
  const selected = invoices.find(i => i.id === selectedId) ?? invoices[0], chosen = clients.find(c => c.id === draftClientId);
  const nextNumber = (period: string) => `${period}-${String(Math.max(0, ...invoices.filter(i => i.number.startsWith(period + "-")).map(i => Number(i.number.split("-")[2]) || 0)) + 1).padStart(3, "0")}`;
  const draft:InvoiceDraft={clientId:draftClientId,date:draftDate,lines:draftLines,taxRate:draftTax,taxMode:draftTaxMode,discountRate:draftDiscount,advance:draftAdvance,payment:draftPayment,note:draftNote,purchaseOrder:draftPurchaseOrder};
  const draftTotals=invoiceTotals(draft);
  const editingInvoice=invoices.find(i=>i.id===editingId);
  function updateDraft(p:Partial<InvoiceDraft>){if(p.clientId!==undefined)setDraftClientId(p.clientId);if(p.date!==undefined)setDraftDate(p.date);if(p.lines!==undefined)setDraftLines(p.lines);if(p.taxRate!==undefined)setDraftTax(p.taxRate);if(p.taxMode!==undefined)setDraftTaxMode(p.taxMode);if(p.discountRate!==undefined)setDraftDiscount(p.discountRate);if(p.advance!==undefined)setDraftAdvance(p.advance);if(p.payment!==undefined)setDraftPayment(p.payment);if(p.note!==undefined)setDraftNote(p.note);if(p.purchaseOrder!==undefined)setDraftPurchaseOrder(p.purchaseOrder);setFormError("");}
  function editInvoice(id:string){const i=invoices.find(x=>x.id===id);if(!i)return;if(closedMonths.includes(i.date.slice(0,7)))return setNotice("Ce mois est clôturé. La facture reste consultable.");setFormError("");setEditingId(i.id);updateDraft({clientId:i.client.id,date:i.date,lines:i.lines.map(l=>({...l})),taxRate:i.taxRate,taxMode:invoiceTotals(i).taxMode,discountRate:i.discountRate||0,advance:i.advance,payment:normalizePayment(i.payment),note:i.note,purchaseOrder:i.purchaseOrder||""});setView("creation");}
  function openStatement(id=""){setStatementClientId(id);setView("situation");setMobileMenu(false);}
  function newInvoice(clientId = "") { setEditingId("");setDraftTaxMode("ht");setDraftDiscount(0);setDraftPurchaseOrder("");setRegisterTab("factures"); const [year, m] = month.split("-").map(Number); const day = Math.min(new Date().getDate(), new Date(year, m, 0).getDate()); setDraftClientId(clientId); setDraftDate(`${month}-${String(day).padStart(2, "0")}`); setDraftLines([emptyLine()]); setDraftTax(19.25); setDraftAdvance(0); setDraftPayment("Espèces"); setDraftNote(""); setFormError(""); setView("creation"); setMobileMenu(false); }
  function saveClient() { if (!clientForm.name.trim()) return; if (clientForm.id) setClients(cs => cs.map(c => c.id === clientForm.id ? { ...clientForm, name: clientForm.name.trim() } : c)); else { const c = { ...clientForm, id: crypto.randomUUID(), name: clientForm.name.trim() }; setClients(cs => [...cs, c]); setDraftClientId(c.id); } setClientDialog(false); setNotice("Client enregistré."); }
  function issue() {
    if(!chosen)return setFormError("Choisissez un client.");
    if(!draftDate||!Number.isFinite(new Date(draftDate+"T12:00:00").getTime()))return setFormError("Choisissez une date valide.");
    const lines=draftLines.filter(l=>l.designation.trim());
    if(!lines.length||draftLines.some(l=>!l.designation.trim()&&l.unitPrice>0)||lines.some(l=>!Number.isFinite(l.quantity)||l.quantity<=0||!Number.isSafeInteger(l.unitPrice)||l.unitPrice<0))return setFormError("Chaque article doit avoir une désignation, une quantité positive et un prix entier.");
    if(!Number.isFinite(draftTax)||draftTax<0||draftTax>100||!Number.isFinite(draftDiscount)||draftDiscount<0||draftDiscount>100)return setFormError("La TVA et la remise doivent être comprises entre 0 et 100 %.");
    if(!Number.isSafeInteger(draftAdvance)||draftAdvance<0||draftAdvance>draftTotals.ttc)return setFormError("L’avance doit être un montant entier compris entre zéro et le total.");
    const period=draftDate.slice(0,7);
    if(closedMonths.includes(period))return setFormError("Ce mois est clôturé.");
    if(editingInvoice&&period!==editingInvoice.date.slice(0,7))return setFormError("La date doit rester dans le mois du numéro de facture.");
    if(editingInvoice&&draftClientId!==editingInvoice.client.id&&(payments.some(p=>p.invoiceId===editingId&&!p.cancelledAt)||credits.some(c=>c.invoiceId===editingId)))return setFormError("Cette facture a des paiements ou des avoirs : conservez le même client.");
    if(editingInvoice){const previousCredits=credits.filter(c=>c.invoiceId===editingId);const financial=(ls:Line[])=>JSON.stringify(ls.map(l=>({id:l.id,quantity:l.quantity,unitPrice:l.unitPrice})));if(previousCredits.some(c=>c.lines?.length)&&(financial(lines)!==financial(editingInvoice.lines)||draftDiscount!==(editingInvoice.discountRate||0)||draftTaxMode!==invoiceTotals(editingInvoice).taxMode||draftTax!==editingInvoice.taxRate))return setFormError("Cette facture a un avoir par article : ses quantités, prix, remise et TVA sont conservés. Les textes restent modifiables.");if(draftTotals.ttc<previousCredits.reduce((n,c)=>n+c.amount,0)||draftTotals.ht<previousCredits.reduce((n,c)=>n+c.ht,0)||draftTotals.tax<previousCredits.reduce((n,c)=>n+c.tax,0))return setFormError("Le nouveau montant ne peut pas être inférieur aux avoirs déjà émis.");for(const line of editingInvoice.lines){const used=previousCredits.flatMap(c=>c.lines??[]).filter(l=>l.sourceLineId===line.id).reduce((n,l)=>n+l.quantity,0);const next=lines.find(l=>l.id===line.id);if(used>0&&(!next||next.quantity<used||next.unitPrice!==line.unitPrice||draftDiscount!==(editingInvoice.discountRate||0)||draftTaxMode!==invoiceTotals(editingInvoice).taxMode||draftTax!==editingInvoice.taxRate))return setFormError("Un article déjà concerné par un avoir doit conserver son prix, sa taxe et au moins la quantité déduite.");}}
    const data={date:draftDate,client:{...chosen},company:editingInvoice?.company??{...company,logo:""},lines:lines.map(l=>({...l})),taxRate:draftTax,taxMode:draftTaxMode,discountRate:draftDiscount,purchaseOrder:draftPurchaseOrder.trim(),advance:draftAdvance,payment:draftPayment,note:draftNote,template:editingInvoice?.template??{...template,document:fixedModel(format)}};
    let invoice:Invoice;
    if(editingInvoice){const {history,...previous}=editingInvoice;invoice={...editingInvoice,...data,revisedAt:new Date().toISOString(),history:[...(history??[]),{...previous,savedAt:new Date().toISOString()}]};setInvoices(items=>items.map(i=>i.id===invoice.id?invoice:i));}
    else{invoice={...data,id:crypto.randomUUID(),number:nextNumber(period)};setInvoices(items=>[...items,invoice]);}
    setSelectedId(invoice.id);setMonth(period);setView("apercu");setEditingId("");setNotice(editingInvoice?"Modifications enregistrées. Le numéro et la version précédente sont conservés.":"Facture "+invoice.number+" enregistrée.");
  }
  function exportBackup() { const data = { clients, company, template, invoices, closedMonths, format, month, payments, credits, sidebarCollapsed, exportedAt: new Date().toISOString() }; const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = `factures-sauvegarde-${new Date().toISOString().slice(0, 10)}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setNotice("Sauvegarde téléchargée : clients, factures, paiements et avoirs."); }
  async function restoreBackup(file?: File) { if (!file) return; try { const d = JSON.parse(await file.text()); if (!Array.isArray(d.clients) || !Array.isArray(d.invoices) || typeof d.company?.name !== "string") throw new Error("Ce fichier n’est pas une sauvegarde de l’application."); if (!window.confirm("Remplacer les données de ce navigateur par cette sauvegarde ? Téléchargez d’abord une copie de vos données actuelles si nécessaire.")) return; setClients(d.clients); setCompany(d.company); setTemplate(d.template ?? initialTemplate); setInvoices(d.invoices); setPayments(d.payments ?? []); setFormat(restoreFormat(d)); setCredits(d.credits ?? []); setClosedMonths(d.closedMonths ?? []); if (d.month) setMonth(d.month); setView("factures"); setNotice("Sauvegarde restaurée."); } catch (e) { setNotice((e as Error).message || "Impossible de lire cette sauvegarde."); } }
  function openAccount(id: string) { setAccountClientId(id); setView("suivi"); setMobileMenu(false); }
  function startPayment(id: string) { const invoice = invoices.find(i => i.id === id); if (!invoice || balance(invoice, payments, credits).due <= 0) return; setPaymentInvoiceId(id); setPaymentAmount(""); setPaymentDate(today()); setPaymentMethod(paymentMethods.includes(normalizePayment(invoice.payment)) ? normalizePayment(invoice.payment) : "Espèces"); setPaymentReference(""); setPaymentError(""); }
  function savePayment() { const invoice = invoices.find(i => i.id === paymentInvoiceId); if (!invoice) return; const amount = Number(paymentAmount); if (!Number.isFinite(amount) || amount <= 0 || !Number.isInteger(amount)) return setPaymentError("Saisissez un montant entier supérieur à zéro."); if (amount > balance(invoice, payments, credits).due) return setPaymentError("Ce montant dépasse le reste à payer. Vérifiez le montant ou choisissez une autre facture."); if (!/^\d{4}-\d{2}-\d{2}$/.test(paymentDate) || !Number.isFinite(new Date(paymentDate + "T12:00:00").getTime())) return setPaymentError("Choisissez la date du paiement."); const entry: Payment = { id: crypto.randomUUID(), invoiceId: invoice.id, amount, date: paymentDate, method: paymentMethod, reference: paymentReference.trim() }; setPayments(p => [...p, entry]); setPaymentInvoiceId(""); setNotice(`Paiement enregistré. Reste à payer : ${money(balance(invoice, [...payments, entry], credits).due)}.`); }
  function openClient(c?: Client) { setClientForm(c ? { ...c } : emptyClient()); setClientDialog(true); }

  function startCredit(id: string) { const invoice = invoices.find(i => i.id === id); if (!invoice || balance(invoice, payments, credits).credited >= balance(invoice, payments, credits).total) return; setCreditInvoiceId(id);setCreditMode("articles");setCreditQuantities({}); setCreditAmount(""); setCreditReason(""); setCreditDate(today()); setCreditError(""); }
  function openCredit(id: string) { setRegisterTab("avoirs"); setSelectedCreditId(id); setView("avoir"); setMobileMenu(false); }
  function issueCredit() {
    const invoice=invoices.find(i=>i.id===creditInvoiceId);if(!invoice)return;
    const selection=creditSelection(invoice,credits,creditQuantities),b=balance(invoice,payments,credits),amount=creditMode==="articles"?selection.amount:Number(creditAmount);
    if(creditMode==="articles"&&(!selection.lines.length||Object.entries(creditQuantities).some(([id,q])=>!Number.isFinite(q)||q<=0||q>(selection.available.find((l:any)=>l.id===id)?.remaining??0))))return setCreditError("Choisissez au moins un article avec une quantité disponible.");
    if(!Number.isSafeInteger(amount)||amount<=0||amount>b.total-b.credited)return setCreditError("Le montant doit être positif et ne pas dépasser le montant encore facturé.");
    if(!creditReason.trim())return setCreditError("Indiquez le motif de l’avoir.");
    if(!creditDate||!Number.isFinite(new Date(creditDate+"T12:00:00").getTime())||creditDate<invoice.date)return setCreditError("Choisissez une date égale ou postérieure à celle de la facture.");
    const period=creditDate.slice(0,7);if(closedMonths.includes(period))return setCreditError("Ce mois est clôturé.");
    const original=invoiceTotals(invoice),previous=credits.filter(c=>c.invoiceId===invoice.id),remainingHt=original.ht-previous.reduce((n,c)=>n+c.ht,0),remainingTax=original.tax-previous.reduce((n,c)=>n+c.tax,0);
    const ht=creditMode==="articles"?selection.ht:Math.max(0,amount-remainingTax,Math.min(remainingHt,Math.round(amount/(1+(original.taxMode==="ttc"?invoice.taxRate:0)/100))));
    const number="AV-"+period+"-"+String(Math.max(0,...credits.filter(c=>c.date.startsWith(period)).map(c=>Number(c.number.split("-").at(-1))||0))+1).padStart(3,"0");
    const credit:CreditNote={id:crypto.randomUUID(),invoiceId:invoice.id,number,date:creditDate,amount,ht,tax:amount-ht,taxRate:invoice.taxRate,taxMode:original.taxMode,lines:creditMode==="articles"?selection.lines:undefined,reason:creditReason.trim(),invoiceNumber:invoice.number,invoiceDate:invoice.date,client:{...invoice.client},company:{...invoice.company,logo:""},format:modelFormat(invoice.template?.document??fixedModel(format))};
    setCredits(cs=>[...cs,credit]);setCreditInvoiceId("");setMonth(period);openCredit(credit.id);setNotice("Avoir enregistré. Le compte client a été mis à jour.");
  }
  const creditInvoice = invoices.find(i => i.id === creditInvoiceId);
  const selectedCredit = credits.find(c => c.id === selectedCreditId);
  const payingInvoice = invoices.find(i => i.id === paymentInvoiceId);
  const nav = (v: View) => { setView(v); setMobileMenu(false); setSearch(""); };
  return <div className={"shell desktop-shell view-" + view + (view === "controle" ? " control-workspace " : " ") + (sidebarCollapsed ? "sidebar-collapsed" : "")}><aside className={`sidebar ${mobileMenu ? "open" : ""}`}><div className="brand"><span>C</span><div><strong>CAPSED</strong><small>FACTURATION</small></div><button className="mobile-close" onClick={() => setMobileMenu(false)} aria-label="Fermer le menu"><X size={20} /></button></div><span className="side-label">GESTION</span><nav aria-label="Navigation principale"><button className={view === "factures" || view === "creation" || view === "apercu" || view === "avoir" ? "active" : ""} onClick={() => nav("factures")} title="Factures & avoirs"><FileText size={20} /> Factures & avoirs</button><button className={view === "clients" || view === "suivi" || view === "situation" ? "active" : ""} onClick={() => nav("clients")} title="Clients & paiements"><Users size={20} /> Clients & paiements</button><button className={view === "modele" ? "active" : ""} onClick={() => nav("modele")} title="Format de facture"><LayoutTemplate size={20} /> Format de facture</button><button className={"settings-nav " + (view === "entreprise" ? "active" : "")} onClick={() => nav("entreprise")} title="Réglages"><Building2 size={20} /> Réglages</button></nav><div className="side-bottom"><button className="backup-link" onClick={exportBackup}><Download size={13} /> Télécharger une sauvegarde</button><label className="backup-link restore-link"><FolderOpen size={13} /> Restaurer une sauvegarde<input type="file" accept="application/json,.json" onChange={e => { restoreBackup(e.target.files?.[0]); e.target.value = ""; }} /></label><p>Votre entreprise. Votre mise en page.</p></div></aside>{mobileMenu && <button className="backdrop" onClick={() => setMobileMenu(false)} aria-label="Fermer le menu" />}
    <div className="main"><header className="topbar workspace-toolbar"><div className="workspace-tools"><button className="sidebar-toggle" onClick={() => setSidebarCollapsed(v => !v)} aria-label={sidebarCollapsed ? "Déplier le menu" : "Replier le menu"}>{sidebarCollapsed ? <PanelLeftOpen size={18}/> : <PanelLeftClose size={18}/>}</button><button className="mobile-menu" onClick={() => setMobileMenu(true)} aria-label="Ouvrir le menu"><Menu size={20}/></button><nav className="workspace-switcher" aria-label="Espaces de travail"><button className={!["clients","suivi","situation","controle"].includes(view) ? "active" : ""} aria-pressed={!["clients","suivi","situation","controle"].includes(view)} onClick={()=>nav("factures")}><FileText size={17}/><span>Facturation</span></button><button className={["clients","suivi","situation"].includes(view) ? "active" : ""} aria-pressed={["clients","suivi","situation"].includes(view)} onClick={()=>nav("clients")}><Users size={17}/><span>Gestion</span></button><button className={view === "controle" ? "active" : ""} aria-pressed={view === "controle"} onClick={()=>nav("controle")} title="Contrôle de l’activité"><Activity size={17}/><span>Contrôle</span></button></nav><button className="notification-trigger" onClick={()=>setNotificationsOpen(true)} aria-label={"Notifications"+(teamRequests.filter(r=>r.receivedAt&&!r.readAt).length ? " · "+teamRequests.filter(r=>r.receivedAt&&!r.readAt).length+" non lues" : "")} title="Notifications"><Bell size={19}/>{teamRequests.some(r=>r.receivedAt&&!r.readAt)&&<span>{teamRequests.filter(r=>r.receivedAt&&!r.readAt).length}</span>}</button></div><div className="workspace-identity"><span className="workspace-company">{company.name}</span><WorkspaceHelp view={view}/><span className="demo-badge">Démo</span></div></header><main className="content">
      {view === "controle" && controlSnapshot && <ControlCenter onLock={lockControlPayment} snapshot={controlSnapshot} requests={controlRequests} connected={controlConnected} onConnection={()=>setControlConnected(v=>!v)} onSync={simulateSync} onSend={r=>{setControlRequests(rs=>[r,...rs]);setNotice("Demande d’essai créée. Elle sera reçue après synchronisation simulée.");}} />}

      {view === "factures" && <InvoiceRegister invoices={invoices} payments={payments} credits={credits} month={month} onMonth={setMonth} tab={registerTab} onTab={setRegisterTab} closed={closedMonths.includes(month)} onClose={() => setCloseDialog(true)} onNew={() => newInvoice()} onInvoice={id => { setRegisterTab("factures"); setSelectedId(id); nav("apercu"); }} onCredit={openCredit} onCreateCredit={startCredit} onPayment={startPayment} onClient={openAccount} onEdit={editInvoice} />}
      {(view === "clients" || view === "suivi") && <ClientAccount clients={clients} invoices={invoices} payments={payments} credits={credits} onStatement={openStatement} onCredit={startCredit} onCreditOpen={openCredit} clientId={view === "suivi" ? accountClientId : ""} onClient={openAccount} onBack={() => nav("clients")} onAdd={() => openClient()} onEdit={id => openClient(clients.find(c => c.id === id))} onInvoice={id => { setSelectedId(id); nav("apercu"); }} onNewInvoice={newInvoice} onPayment={startPayment} lockedPaymentIds={teamLockedPaymentIds} onCancel={id=>{if(teamLockedPaymentIds.includes(id))setNotice("Ce paiement est validé et verrouillé.");else setCancelPaymentId(id);}} />}
      {view === "modele" && <FormatSettings format={format} onChange={setFormat} invoice={{ ...(selected ?? initialInvoices[0]), company }} words={words} />}
      {view === "entreprise" && <><div className="heading"><div><small>INFORMATIONS PERMANENTES</small><h1>Réglages de l’entreprise</h1></div></div><section className="card settings"><div className="settings-title"><span><Building2 size={25} /></span><div><h2>Coordonnées de l’entreprise</h2></div></div><div className="grid-fields">{([["name", "Nom de l’entreprise"], ["subtitle", "Activité"], ["address", "Adresse"], ["phone", "Téléphone"], ["email", "Adresse e-mail"], ["website", "Site web"], ["niu", "NIU"], ["rc", "RCCM"]] as [keyof Company, string][]).map(([key, label]) => <label className="field" key={key}><span>{label}</span><input value={company[key]} onChange={e => setCompany(c => ({ ...c, [key]: e.target.value }))} /></label>)}</div><div className="data-backups"><button className="outline" onClick={exportBackup}><Download size={15} /> Sauvegarder mes données</button><label className="restore-link"><FolderOpen size={15} /> Restaurer une sauvegarde<input type="file" accept="application/json,.json" onChange={e => { restoreBackup(e.target.files?.[0]); e.target.value = ""; }} /></label></div></section></>}
      {view === "creation" && <><div className="back-line"><button onClick={()=>nav(editingId?"apercu":"factures")}><ArrowLeft size={18}/> Retour</button></div><InvoiceComposer draft={draft} onChange={updateDraft} clients={clients} onClient={()=>openClient()} onEditClient={()=>chosen&&openClient(chosen)} onSave={issue} error={formError} number={editingInvoice?.number}/></>}
      {view === "situation" && <><div className="back-line no-print"><button onClick={()=>statementClientId?openAccount(statementClientId):nav("clients")}><ArrowLeft size={18}/> Retour aux clients</button></div><div className="heading no-print"><h1>{statementClientId?"Situation du client":"Situation globale"}</h1><div className="heading-actions"><button className="outline" onClick={()=>downloadStatement(clients,invoices,payments,credits,statementClientId)}><Download size={17}/> Extraire en CSV</button><button className="primary" onClick={()=>window.print()}><Printer size={18}/> Imprimer / PDF</button></div></div><div className="paper-shell"><DocumentPreview title="Situation des clients"><AccountStatement clients={clients} invoices={invoices} payments={payments} credits={credits} clientId={statementClientId} format={format}/></DocumentPreview></div></>}
      {view === "apercu" && selected && <><div className="back-line no-print"><button onClick={() => nav("factures")} title="Factures"><ArrowLeft size={18} /> Retour aux factures</button></div><div className="heading no-print"><div><small>FACTURE ÉMISE</small><h1>{selected.number}</h1><p>Facture du {dateLabel(selected.date)} pour {selected.client.name}.</p></div><div className="heading-actions"><button className="outline" disabled={closedMonths.includes(selected.date.slice(0,7))} onClick={()=>editInvoice(selected.id)}><Pencil size={17}/> Modifier la facture</button><button className="primary" onClick={() => window.print()}><Printer size={18} /> Imprimer / PDF</button></div></div>{selected.history?.length ? <details className="invoice-revisions no-print"><summary>{selected.history.length} version{selected.history.length>1?"s":""} précédente{selected.history.length>1?"s":""} conservée{selected.history.length>1?"s":""}</summary>{selected.history.map((version,index)=><details key={index}><summary>Version {index+1} · {money(invoiceTotals(version).ttc)} · avant modification</summary><DocumentPreview title="Version précédente"><Paper invoice={version}/></DocumentPreview></details>)}</details>:null}<div className="invoice-payment-strip no-print"><div><PaymentStatus invoice={selected} payments={payments} credits={credits} /><span>Reçu : <strong>{money(balance(selected, payments, credits).received)}</strong></span>{balance(selected, payments, credits).credited > 0 && <span>Avoirs : <strong>− {money(balance(selected, payments, credits).credited)}</strong></span>}{balance(selected, payments, credits).refund > 0 && <span>À restituer : <strong>{money(balance(selected, payments, credits).refund)}</strong></span>}<span>Reste à payer : <strong>{money(balance(selected, payments, credits).due)}</strong></span></div><div><button className="outline" onClick={() => openAccount(selected.client.id)}>Voir le compte client</button>{balance(selected, payments, credits).credited < balance(selected, payments, credits).total && <button className="outline" onClick={() => startCredit(selected.id)}>Créer un avoir</button>}{balance(selected, payments, credits).due > 0 && <button className="primary" onClick={() => startPayment(selected.id)}>Enregistrer un paiement</button>}</div></div><div className="delivery-demo-line no-print"><span>Remise au client · simulation</span>{invoiceDeliveries.some(d=>d.invoiceId===selected.id) ? <strong><Check size={14}/> Remise déclarée sur ce poste</strong> : <button className="outline" onClick={()=>{setInvoiceDeliveries(ds=>[...ds,{invoiceId:selected.id,declaredAt:new Date().toISOString()}]);setNotice("Remise simulée. Le contrôle sera actualisé après synchronisation.");}}>Simuler la remise du document</button>}</div><div className="paper-shell"><DocumentPreview title="Aperçu de la facture"><Paper invoice={selected} /></DocumentPreview></div></>}
      {view === "avoir" && selectedCredit && <><div className="back-line no-print"><button onClick={() => openAccount(selectedCredit.client.id)}><ArrowLeft size={18} /> Compte du client</button><button onClick={() => { setSelectedId(selectedCredit.invoiceId); nav("apercu"); }}>Voir la facture d’origine</button></div><div className="heading no-print"><div><small>FACTURE D’AVOIR</small><h1>{selectedCredit.number}</h1><p>{selectedCredit.client.name} · liée à la facture {selectedCredit.invoiceNumber}</p></div><button className="primary" onClick={() => window.print()}><Printer size={18} /> Imprimer / PDF</button></div><div className="paper-shell"><DocumentPreview title="Aperçu de l’avoir"><CreditPaper credit={selectedCredit} /></DocumentPreview></div></>}
    </main><footer className="app-statusbar"><span><span className="status-dot" /> Stockage : ce navigateur</span><span>{monthLabel(month)}<i /> FCFA</span></footer></div>
    {notice && <div className="toast" role="status"><Check size={18} /> {notice}<button onClick={() => setNotice("")} aria-label="Fermer"><X size={16} /></button></div>}
    <Dialog open={notificationsOpen} onOpenChange={setNotificationsOpen}><DialogContent className="notifications-drawer"><DialogHeader className="sr-only"><DialogTitle>Notifications de l’équipe</DialogTitle><DialogDescription>Demandes de vérification reçues sur le poste simulé.</DialogDescription></DialogHeader><TeamNotifications requests={teamRequests} connected={controlConnected} onConnection={()=>setControlConnected(v=>!v)} onSync={simulateSync} onRead={id=>setTeamRequests(rs=>rs.map(r=>r.id===id?{...r,readAt:r.readAt??new Date().toISOString()}:r))} onResolve={(id,response)=>{setTeamRequests(rs=>rs.map(r=>r.id===id?{...r,resolvedAt:new Date().toISOString(),response}:r));setNotice("Réponse enregistrée sur le poste simulé. Synchronisez pour la transmettre.");}} onInvoice={id=>{setNotificationsOpen(false);setSelectedId(id);nav("apercu");}} onPayment={id=>{setNotificationsOpen(false);startPayment(id);}} payments={payments} invoices={invoices} credits={credits} /></DialogContent></Dialog>
    <CreditComposer invoice={creditInvoice} credits={credits} payments={payments} mode={creditMode} onMode={setCreditMode} quantities={creditQuantities} onQuantities={setCreditQuantities} amount={creditAmount} onAmount={setCreditAmount} reason={creditReason} onReason={setCreditReason} date={creditDate} onDate={setCreditDate} error={creditError} onSave={issueCredit} onClose={()=>setCreditInvoiceId("")}/>
    <Dialog open={!!payingInvoice} onOpenChange={open => { if (!open) setPaymentInvoiceId(""); }}><DialogContent className="payment-dialog"><DialogHeader><DialogTitle>Enregistrer un paiement</DialogTitle><DialogDescription>{payingInvoice?.client.name} · facture {payingInvoice?.number}</DialogDescription></DialogHeader>{payingInvoice && <form onSubmit={e => { e.preventDefault(); savePayment(); }}>{invoices.filter(i => i.client.id === payingInvoice.client.id && balance(i, payments, credits).due > 0).length > 1 && <label className="field payment-invoice-choice"><span>Pour quelle facture ?</span><select value={paymentInvoiceId} onChange={e => startPayment(e.target.value)}>{invoices.filter(i => i.client.id === payingInvoice.client.id && balance(i, payments, credits).due > 0).map(i => <option key={i.id} value={i.id}>{i.number} · reste {money(balance(i, payments, credits).due)}</option>)}</select></label>}<div className="payment-due-box"><span>Il reste à payer</span><strong>{money(balance(payingInvoice, payments, credits).due)}</strong></div><label className="field payment-amount-field"><span>Combien avez-vous reçu ? (FCFA)</span><input autoFocus type="number" min="1" step="1" max={balance(payingInvoice, payments, credits).due} value={paymentAmount} placeholder="Ex. 50 000" onChange={e => { setPaymentAmount(e.target.value); setPaymentError(""); }} required /></label><button type="button" className="fill-balance" onClick={() => setPaymentAmount(String(balance(payingInvoice, payments, credits).due))}>Le client a payé tout le reste</button><div className="grid-fields payment-details"><label className="field"><span>Date du paiement</span><input required type="date" value={paymentDate} onChange={e => setPaymentDate(e.target.value)} /></label><label className="field"><span>Comment a-t-il payé ?</span><select value={paymentMethod} onChange={e => setPaymentMethod(e.target.value)}>{paymentMethods.map(m => <option key={m}>{m}</option>)}</select></label></div><details className="payment-note"><summary>Ajouter une référence (facultatif)</summary><label className="field"><span>Référence ou note</span><input value={paymentReference} onChange={e => setPaymentReference(e.target.value)} placeholder="Ex. référence du virement" /></label></details>{paymentAmount && Number(paymentAmount) > 0 && <div className="payment-after">Après ce paiement, il restera <strong>{money(Math.max(0, balance(payingInvoice, payments, credits).due - Number(paymentAmount)))}</strong></div>}{paymentError && <p className="payment-error" role="alert">{paymentError}</p>}<div className="dialog-actions"><button type="button" className="outline" onClick={() => setPaymentInvoiceId("")}>Annuler</button><button type="submit" className="primary">Enregistrer le paiement</button></div></form>}</DialogContent></Dialog>
    <AlertDialog open={!!cancelPaymentId} onOpenChange={open => { if (!open) setCancelPaymentId(""); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Annuler ce paiement saisi par erreur ?</AlertDialogTitle><AlertDialogDescription>Le montant sera retiré des paiements reçus et le reste à payer sera recalculé. L’entrée restera visible comme annulée.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Garder le paiement</AlertDialogCancel><AlertDialogAction onClick={() => { if(teamLockedPaymentIds.includes(cancelPaymentId)){setCancelPaymentId("");setNotice("Ce paiement est validé et verrouillé.");return;} setPayments(ps => ps.map(p => p.id === cancelPaymentId ? { ...p, cancelledAt: new Date().toISOString() } : p)); setCancelPaymentId(""); setNotice("Paiement annulé. Le compte client a été mis à jour."); }}>Annuler ce paiement</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Dialog open={clientDialog} onOpenChange={setClientDialog}><DialogContent className="client-dialog"><DialogHeader><DialogTitle>{clientForm.id ? "Modifier le client" : "Ajouter un client"}</DialogTitle><DialogDescription>Seul le nom est obligatoire. Les informations manquantes ne seront pas imprimées.</DialogDescription></DialogHeader><div className="grid-fields">{([["name", "Nom du client *"], ["contact", "Personne à contacter"], ["address", "Adresse"], ["phone", "Téléphone"], ["email", "Adresse e-mail"], ["niu", "NIU"], ["rc", "RCCM"]] as [keyof Client, string][]).map(([key, label]) => <label className={`field ${key === "address" ? "wide" : ""}`} key={key}><span>{label}</span><input value={clientForm[key]} onChange={e => setClientForm(c => ({ ...c, [key]: e.target.value }))} /></label>)}</div><div className="dialog-actions"><button className="outline" onClick={() => setClientDialog(false)}>Annuler</button><button className="primary" disabled={!clientForm.name.trim()} onClick={saveClient}>Enregistrer le client</button></div></DialogContent></Dialog>
    <AlertDialog open={closeDialog} onOpenChange={setCloseDialog}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Clôturer {monthLabel(month)} ?</AlertDialogTitle><AlertDialogDescription>Vous ne pourrez plus émettre de nouvelle facture pour ce mois dans cette démonstration. Les factures existantes resteront consultables.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annuler</AlertDialogCancel><AlertDialogAction onClick={() => { setClosedMonths(ms => [...ms, month]); const [y, m] = month.split("-").map(Number); const next = new Date(y, m, 1); setMonth(`${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, "0")}`); setNotice(`${monthLabel(month)} clôturé. Le mois suivant est ouvert.`); }}>Clôturer et passer au mois suivant</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
