import { invoiceTotals, lineAmount, normalizePayment, printedQuantity } from "./invoice-math";
import { clientDetailLines } from "./client-details";
type Cell = string | number;
const xml=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]!)).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,"");
export function downloadBlob(data:Blob,name:string){const url=URL.createObjectURL(data),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function zip(files:Record<string,string>){
 const encoder=new TextEncoder(),chunks:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;
 const crc=(data:Uint8Array)=>{let n=0xffffffff;for(const b of data){n^=b;for(let i=0;i<8;i++)n=(n>>>1)^((n&1)?0xedb88320:0);}return(n^0xffffffff)>>>0;};
 for(const [name,value] of Object.entries(files)){const path=encoder.encode(name),data=encoder.encode(value),sum=crc(data);const header=new Uint8Array(30+path.length),v=new DataView(header.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x0800,true);v.setUint32(14,sum,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,path.length,true);header.set(path,30);chunks.push(header,data);
 const entry=new Uint8Array(46+path.length),e=new DataView(entry.buffer);e.setUint32(0,0x02014b50,true);e.setUint16(4,20,true);e.setUint16(6,20,true);e.setUint16(8,0x0800,true);e.setUint32(16,sum,true);e.setUint32(20,data.length,true);e.setUint32(24,data.length,true);e.setUint16(28,path.length,true);e.setUint32(42,offset,true);entry.set(path,46);central.push(entry);offset+=header.length+data.length;}
 const end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,central.length,true);e.setUint16(10,central.length,true);e.setUint32(12,central.reduce((n,c)=>n+c.length,0),true);e.setUint32(16,offset,true);
 return new Blob([...chunks,...central,end] as BlobPart[],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
}
export function downloadExcel(rows:Cell[][],filename:string){
 const col=(n:number):string=>n<26?String.fromCharCode(65+n):col(Math.floor(n/26)-1)+String.fromCharCode(65+n%26);
 const data=rows.map((row,r)=>'<row r="'+(r+1)+'">'+row.map((cell,c)=>{const ref=col(c)+(r+1);return typeof cell==="number"&&Number.isFinite(cell)?'<c r="'+ref+'" s="1"><v>'+cell+'</v></c>':'<c r="'+ref+'" t="inlineStr"><is><t xml:space="preserve">'+xml(cell)+'</t></is></c>';}).join("")+'</row>').join("");
 const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
 const files={
 "[Content_Types].xml":'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
 "_rels/.rels":'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 "xl/workbook.xml":'<workbook xmlns="'+ns+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Document" sheetId="1" r:id="rId1"/></sheets></workbook>',
 "xl/_rels/workbook.xml.rels":'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
 "xl/styles.xml":'<styleSheet xmlns="'+ns+'"><fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="3" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"><alignment vertical="top"/></xf></cellXfs></styleSheet>',
 "xl/worksheets/sheet1.xml":'<worksheet xmlns="'+ns+'"><cols><col min="1" max="1" width="48" customWidth="1"/><col min="2" max="2" width="30" customWidth="1"/><col min="3" max="8" width="20" customWidth="1"/></cols><sheetData>'+data+'</sheetData><pageSetup paperSize="9" orientation="portrait"/></worksheet>'
 };downloadBlob(zip(files),filename.endsWith(".xlsx")?filename:filename+".xlsx");
}
export function exportInvoice(i:any,words:(n:number)=>string){
 const t=invoiceTotals(i),rows:Cell[][]=[[i.company.name],["FACTURE",i.number],["Date",i.date],["Client",i.client.name],...clientDetailLines(i.client).map(s=>[s]),...(i.purchaseOrder?.trim()?[["BC",i.purchaseOrder]]:[]),[],["Désignation","Destination","Quantité","Prix unitaire HT","Montant HT"],...i.lines.map((l:any)=>[l.designation,l.destination,Number.isInteger(l.quantity)?l.quantity:printedQuantity(l.quantity),Math.round(l.unitPrice),lineAmount(l)]),[],["Montant de départ",t.subtotal],...(t.discount?[["Remise",-t.discount]]:[]),["Montant HT",t.ht],...(t.taxMode==="ttc"?[["TVA",t.tax],["Total TTC",t.ttc]]:[]),...(i.advance?[["Avance",-i.advance],["Reste à payer",t.due]]:[]),[],["Arrêtée la présente facture à la somme de "+words(t.ttc).toUpperCase()+" FRANCS CFA."],["Mode de règlement",normalizePayment(i.payment)],...(i.note?.trim()?[[i.note]]:[]),["La Direction."],["Merci pour votre confiance."],["Suarl au capital de 1 000 000Fcfa B.P: 3463 Douala - Cameroun Tél: (237) 243 55 31 56 / 674 55 73 73 / 699 92 80 02 Email: capsedsarl@gmail.com"],["RCCM N° : RC/DLA/2016B599 NIU: M021612485549 S N° : Employeur CNPS: 351-0122533-000-B CPTE Bancaire SGBC N°: 10003 01900 05190629651 50"]];
 downloadExcel(rows,"facture-"+i.number+".xlsx");
}
