import { useEffect, useRef, useState } from "react";
import { ArrowLeft, Plus, Copy, Trash2, Undo2, Redo2, Image, Type, Grip, Eye, MousePointer2, Check, X } from "lucide-react";
import { BLOCKS, createModel, makeBlock, PAGE_W, PAGE_H, imageData } from "./document-model";
import type { DocumentBlock, DocumentModel, BlockKind } from "./document-model";
import { BlockContent, blockStyle, DocumentPages } from "./document-renderer";

export default function TemplateStudio({ models, onChange, activeId, onActive, invoice, words }: {
  models: DocumentModel[]; onChange: (models: DocumentModel[]) => void; activeId: string; onActive: (id: string) => void; invoice: any; words: (n: number) => string;
}) {
  const [editing, setEditing] = useState<string | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [inlineText, setInlineText] = useState<string | null>(null);
  const [preview, setPreview] = useState(false), [adding, setAdding] = useState(false);
  const [scale, setScale] = useState(.65), [message, setMessage] = useState("");
  const [past, setPast] = useState<DocumentModel[]>([]), [future, setFuture] = useState<DocumentModel[]>([]);
  const holder = useRef<HTMLDivElement>(null);
  const drag = useRef<{ id: string; mode: "move" | "resize"; startX: number; startY: number; block: DocumentBlock; before: DocumentModel } | null>(null);
  const model = models.find(m => m.id === editing);
  const block = model?.blocks.find(b => b.id === selected);
  useEffect(() => { if (!holder.current) return; const observer = new ResizeObserver(entries => setScale(Math.min(.9, Math.max(.28, (entries[0].contentRect.width - 48) / PAGE_W)))); observer.observe(holder.current); return () => observer.disconnect(); }, [editing, preview]);
  useEffect(() => { if (!message) return; const t = setTimeout(() => setMessage(""), 3500); return () => clearTimeout(t); }, [message]);
  function replace(next: DocumentModel, remember = true) {
    if (remember && model) { setPast(p => [...p.slice(-39), structuredClone(model)]); setFuture([]); }
    onChange(models.map(m => m.id === next.id ? next : m));
  }
  function update(patch: Partial<DocumentBlock>) { if (model && block) replace({ ...model, blocks: model.blocks.map(b => b.id === block.id ? { ...b, ...patch } : b) }); }
  function open(id: string) { setEditing(id); setSelected(null); setPreview(false); setPast([]); setFuture([]); }
  function addModel(style: "blank" | "reference" | "editorial") { const m = createModel(style); onChange([...models, m]); setAdding(false); open(m.id); }
  function addBlock(kind: BlockKind, x = 48, y = 48) { if (!model) return; const b = makeBlock(kind, x, y); if (kind === "lines" && model.blocks.some(b => b.kind === "lines")) return setMessage("Un tableau de prestations suffit : il contient toutes les lignes de la facture."); replace({ ...model, blocks: [...model.blocks, b] }); setSelected(b.id); }
  function remove() { if (!model || !block) return; replace({ ...model, blocks: model.blocks.filter(b => b.id !== block.id) }); setSelected(null); }
  function duplicate() { if (!model || !block) return; if (block.kind === "lines") return setMessage("Le tableau de prestations est unique sur la page."); const copy = { ...structuredClone(block), id: crypto.randomUUID(), x: Math.min(PAGE_W - block.w, block.x + 16), y: Math.min(PAGE_H - block.h, block.y + 16) }; replace({ ...model, blocks: [...model.blocks, copy] }); setSelected(copy.id); }
  function undo() { if (!model || !past.length) return; setFuture(f => [...f, model]); const next = past[past.length - 1]; setPast(p => p.slice(0, -1)); replace(next, false); }
  function redo() { if (!model || !future.length) return; setPast(p => [...p, model]); const next = future[future.length - 1]; setFuture(f => f.slice(0, -1)); replace(next, false); }
  function pointerDown(e: React.PointerEvent, b: DocumentBlock, mode: "move" | "resize") {
    if ((e.target as HTMLElement).tagName === "TEXTAREA") return;
    if (e.button !== 0 || !model) return; e.preventDefault(); e.stopPropagation(); setSelected(b.id);
    e.currentTarget.setPointerCapture(e.pointerId); drag.current = { id: b.id, mode, startX: e.clientX, startY: e.clientY, block: { ...b }, before: structuredClone(model) };
  }
  function pointerMove(e: React.PointerEvent) {
    const d = drag.current; if (!d || !model) return;
    const dx = (e.clientX - d.startX) / scale, dy = (e.clientY - d.startY) / scale;
    const snap = (n: number) => e.altKey ? Math.round(n) : Math.round(n / 4) * 4;
    const patch = d.mode === "move" ? { x: Math.max(0, Math.min(PAGE_W - d.block.w, snap(d.block.x + dx))), y: Math.max(0, Math.min(PAGE_H - d.block.h, snap(d.block.y + dy))) } : { w: Math.max(60, Math.min(PAGE_W - d.block.x, snap(d.block.w + dx))), h: Math.max(d.block.kind === "rule" ? 4 : 24, Math.min(PAGE_H - d.block.y, snap(d.block.h + dy))) };
    replace({ ...model, blocks: model.blocks.map(b => b.id === d.id ? { ...b, ...patch } : b) }, false);
  }
  function pointerUp() { if (drag.current) { const before = drag.current.before; setPast(p => [...p.slice(-39), before]); setFuture([]); drag.current = null; } }
  async function upload(file?: File) { if (!file) return; try { const image = await imageData(file); update({ image }); } catch (e) { setMessage((e as Error).message); } }
  const label = (kind: BlockKind) => BLOCKS.find(b => b.kind === kind)?.label;
  if (!model) return <>
    <div className="heading"><div><small>VOTRE ATELIER</small><h1>Une facture à votre image.</h1><p>Composez une fois. Retrouvez votre mise en page à chaque facture.</p></div><button className="primary" onClick={() => setAdding(true)}><Plus size={18} /> Créer un modèle</button></div>
    <div className="model-gallery">{models.map(m => <article className="model-card" key={m.id}>
      <button className="model-thumbnail" onClick={() => open(m.id)} aria-label={`Modifier ${m.name}`}><div className="thumbnail-page"><DocumentPages model={m} invoice={invoice} words={words} /></div><span className="edit-overlay">Ouvrir l’atelier <span>↗</span></span></button>
      <div className="model-card-meta"><span>{String(models.indexOf(m) + 1).padStart(2, "0")} / MODÈLE</span><h2>{m.name}</h2><div><button className="text-link" onClick={() => open(m.id)}>Modifier <span>↗</span></button><button className={activeId === m.id ? "model-default chosen-default" : "model-default"} onClick={() => onActive(m.id)}>{activeId === m.id ? <><Check size={13} /> Par défaut</> : "Utiliser par défaut"}</button></div></div>
    </article>)}<button className="blank-model-card" onClick={() => { addModel("blank"); }}><Plus size={28} /><h2>Une page blanche</h2><p>Votre idée, votre disposition.</p></button></div>
    <div className="model-explainer"><span>01</span><p>Placez vos textes, images et tableaux.</p><span>02</span><p>Ajoutez les blocs client, prestations et totaux.</p><span>03</span><p>Choisissez ce modèle à la création d’une facture.</p></div>
    {adding && <div className="studio-modal-backdrop"><section className="studio-modal" role="dialog" aria-modal="true" aria-labelledby="new-model-title"><button className="modal-close" onClick={() => setAdding(false)} aria-label="Fermer"><X /></button><small>UN NOUVEAU DÉPART</small><h2 id="new-model-title">Comment voulez-vous commencer ?</h2><p>Tout pourra être déplacé et modifié ensuite.</p><button onClick={() => addModel("blank")}><strong>Page blanche</strong><span>Placez librement chaque élément.</span><Plus /></button><button onClick={() => addModel("reference")}><strong>Facture classique</strong><span>Une base inspirée de votre facture CAPSED.</span><ArrowLeft style={{ transform: "rotate(180deg)" }} /></button><button onClick={() => addModel("editorial")}><strong>Modèle éditorial</strong><span>Une base claire avec un accent vert.</span><ArrowLeft style={{ transform: "rotate(180deg)" }} /></button></section></div>}
  </>;
  return <div className="studio">
    <div className="studio-bar"><button className="icon-text" onClick={() => setEditing(null)}><ArrowLeft size={16} /> Modèles</button><input className="model-name-input" aria-label="Nom du modèle" value={model.name} onChange={e => replace({ ...model, name: e.target.value })} /><span className="studio-autosave"><Check size={13} /> Enregistré</span><div className="studio-bar-actions"><button title="Annuler" aria-label="Annuler" disabled={!past.length} onClick={undo}><Undo2 size={18} /></button><button title="Rétablir" aria-label="Rétablir" disabled={!future.length} onClick={redo}><Redo2 size={18} /></button><button className="outline" onClick={() => setPreview(p => !p)}>{preview ? <MousePointer2 size={16} /> : <Eye size={16} />}{preview ? "Composer" : "Aperçu"}</button><button className="primary" onClick={() => { onActive(model.id); setMessage("Ce modèle sera proposé pour vos prochaines factures."); }}><Check size={16} /> Utiliser</button></div></div>
    <div className={`studio-layout ${preview ? "studio-preview-mode" : ""}`}>
      {!preview && <aside className="block-library"><small>AJOUTER UN ÉLÉMENT</small><h3>Que voulez-vous ajouter ?</h3><p>Cliquez sur un élément. Déplacez-le ensuite sur la page.</p><div className="block-library-items">{BLOCKS.filter(item => ["text", "image", "company", "client", "lines", "totals", "signature", "footer"].includes(item.kind)).map((item, n) => <button draggable key={item.kind} onDragStart={e => { e.dataTransfer.setData("application/invoice-block", item.kind); e.dataTransfer.effectAllowed = "copy"; }} onClick={() => addBlock(item.kind, 48 + (model.blocks.length % 3) * 24, 48 + (model.blocks.length % 9) * 80)}><span className="block-number">{String(n + 1).padStart(2, "0")}</span><span><strong>{item.label}</strong><small>{item.hint}</small></span><Grip size={13} /></button>)}</div><details className="more-blocks"><summary>Autres éléments</summary>{BLOCKS.filter(item => !["text", "image", "company", "client", "lines", "totals", "signature", "footer"].includes(item.kind)).map(item => <button key={item.kind} onClick={() => addBlock(item.kind)}><Plus size={14} /> {item.label}</button>)}</details><div className="library-help"><strong>Les blocs font le travail.</strong><p>Client, numéro, prestations et totaux se remplissent à chaque nouvelle facture.</p></div></aside>}
      <div className="studio-canvas-area" ref={holder}><div className="canvas-caption"><span>{preview ? "APERÇU AVEC DES DONNÉES D’EXEMPLE" : "PAGE A4 · GLISSEZ POUR DÉPLACER"}</span><span>{Math.round(scale * 100)} %</span></div>
        {preview ? <div className="canvas-scale-wrap" style={{ width: PAGE_W * scale, height: PAGE_H * scale }}><div style={{ transform: `scale(${scale})`, transformOrigin: "top left" }}><DocumentPages model={model} invoice={invoice} words={words} /></div></div> :
        <div className="canvas-scale-wrap" style={{ width: PAGE_W * scale, height: PAGE_H * scale }}><div className="editor-page" tabIndex={0} style={{ width: PAGE_W, height: PAGE_H, transform: `scale(${scale})`, transformOrigin: "top left" }} onPointerDown={() => setSelected(null)} onDragOver={e => { e.preventDefault(); e.dataTransfer.dropEffect = "copy"; }} onDrop={e => { e.preventDefault(); const kind = e.dataTransfer.getData("application/invoice-block") as BlockKind; if (!BLOCKS.some(b => b.kind === kind)) return; const rect = e.currentTarget.getBoundingClientRect(); addBlock(kind, (e.clientX - rect.left) / scale, (e.clientY - rect.top) / scale); }} onKeyDown={e => { if ((e.target as HTMLElement).isContentEditable || /INPUT|TEXTAREA/.test((e.target as HTMLElement).tagName)) return; if ((e.ctrlKey || e.metaKey) && e.key === "z") { e.preventDefault(); e.shiftKey ? redo() : undo(); } if (e.key === "Delete" || e.key === "Backspace") { e.preventDefault(); remove(); } if (block && ["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"].includes(e.key)) { e.preventDefault(); const d = e.shiftKey ? 10 : 1; update({ x: Math.max(0, Math.min(PAGE_W - block.w, block.x + (e.key === "ArrowLeft" ? -d : e.key === "ArrowRight" ? d : 0))), y: Math.max(0, Math.min(PAGE_H - block.h, block.y + (e.key === "ArrowUp" ? -d : e.key === "ArrowDown" ? d : 0))) }); } }}>
          {!model.blocks.length && <div className="blank-canvas-hint"><Type size={35} /><h2>Votre page commence ici.</h2><p>Choisissez un bloc à gauche,<br />ou glissez-le à l’endroit qui vous plaît.</p></div>}
          {model.blocks.map(b => <div key={b.id} className={`document-block editor-block kind-${b.kind} ${selected === b.id ? "is-selected" : ""}`} style={blockStyle(b)} onPointerDown={e => pointerDown(e, b, "move")} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onDoubleClick={() => { setSelected(b.id); if (["text", "signature", "footer", "payment"].includes(b.kind)) setInlineText(b.id); }}>
            <div className="block-content">{inlineText === b.id ? <textarea autoFocus aria-label="Modifier le texte sur la page" className="inline-block-text" value={b.text} onPointerDown={e => e.stopPropagation()} onChange={e => update({ text: e.target.value })} onBlur={() => setInlineText(null)} onKeyDown={e => { if (e.key === "Escape") setInlineText(null); }} /> : <BlockContent block={b} invoice={invoice} words={words} />}</div>{selected === b.id && <><span className="selection-label">{label(b.kind)}</span><button className="resize-handle" aria-label="Redimensionner le bloc" onPointerDown={e => pointerDown(e, b, "resize")} onPointerMove={pointerMove} onPointerUp={pointerUp} /></>}
          </div>)}
        </div></div>}
        <p className="canvas-help">{preview ? "Les données d’exemple seront remplacées par celles de votre facture." : "Double-cliquez un texte pour écrire. Glissez un bloc pour le déplacer, son coin pour l’agrandir. Vos changements sont enregistrés automatiquement."}</p>
      </div>
      {!preview && <aside className="block-inspector">{block ? <><small>ÉLÉMENT SÉLECTIONNÉ</small><h3>{label(block.kind)}</h3><div className="inspector-actions"><button onClick={duplicate}><Copy size={14} /> Dupliquer</button><button onClick={remove}><Trash2 size={14} /> Retirer</button></div>
        {["text", "signature", "footer", "payment"].includes(block.kind) && <label className="field"><span>Votre texte</span><textarea id="block-text" rows={5} value={block.text} onChange={e => update({ text: e.target.value })} placeholder={block.kind === "footer" ? "Vide : coordonnées de l’entreprise" : "Écrivez ici…"} /></label>}
        {["text", "footer"].includes(block.kind) && <div className="token-help"><span>Insérer une valeur automatique</span><div>{["client", "entreprise", "numero", "date"].map(t => <button key={t} onClick={() => update({ text: block.text + ` {{${t}}}` })}>{t}</button>)}</div>{block.kind === "table" && <small>Dans une case : {'{{client}}, {{numero}}…'}</small>}</div>}
        {block.kind === "image" && <><label className="outline image-upload"><Image size={16} />{block.image ? "Remplacer l’image" : "Choisir une image"}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => upload(e.target.files?.[0])} /></label><label className="field"><span>Affichage de l’image</span><select value={block.imageFit ?? "contain"} onChange={e => update({ imageFit: e.target.value as "contain" | "cover" })}><option value="contain">Voir l’image entière</option><option value="cover">Remplir le bloc</option></select></label><p className="inspector-hint">L’image est ajustée dans le bloc. Déplacez et agrandissez-le librement.</p></>}
        {block.kind === "lines" && <div className="table-headings-editor"><strong>Titres des colonnes</strong>{(block.headers ?? ["Contrat", "Désignation", "Destination", "Volume / Qté", "P.U.", "Montant"]).map((h, index) => <label className="field" key={index}><span>Colonne {index + 1}</span><input value={h} onChange={e => update({ headers: (block.headers ?? ["Contrat", "Désignation", "Destination", "Volume / Qté", "P.U.", "Montant"]).map((value, n) => n === index ? e.target.value : value) })} /></label>)}</div>}
        {block.kind === "table" && <><div className="custom-cell-editor">{block.cells?.map((row, r) => <div key={r}>{row.map((cell, c) => <input aria-label={`Ligne ${r + 1}, colonne ${c + 1}`} key={c} value={cell} onChange={e => update({ cells: block.cells!.map((rr, ri) => rr.map((cc, ci) => ri === r && ci === c ? e.target.value : cc)) })} />)}</div>)}</div><div className="table-dimension-buttons"><button onClick={() => update({ cells: [...block.cells!, Array(block.cells![0].length).fill("")] })}>+ Ligne</button><button onClick={() => update({ cells: block.cells!.map(r => [...r, ""]) })}>+ Colonne</button><button disabled={block.cells!.length < 2} onClick={() => update({ cells: block.cells!.slice(0, -1) })}>− Ligne</button><button disabled={block.cells![0].length < 2} onClick={() => update({ cells: block.cells!.map(r => r.slice(0, -1)) })}>− Colonne</button></div></>}
        <div className="inspector-divider" /><div className="inspector-two"><label className="field"><span>Taille du texte</span><input type="number" min={8} max={72} value={block.fontSize} onChange={e => update({ fontSize: Math.max(8, Math.min(72, Number(e.target.value))) })} /></label><label className="field"><span>Couleur</span><input type="color" value={block.color} onChange={e => update({ color: e.target.value })} /></label></div>
        <div className="alignment-options">{(["left", "center", "right"] as const).map((a, n) => <button key={a} className={block.align === a ? "selected" : ""} onClick={() => update({ align: a })}>{["Gauche", "Centre", "Droite"][n]}</button>)}<button className={block.bold ? "selected" : ""} onClick={() => update({ bold: !block.bold })}><b>G</b></button></div>
        <details className="advanced-model-settings"><summary>Plus de réglages</summary><div className="inspector-divider" /><label className="field"><span>Placement rapide</span><select value="" onChange={e => { const v = e.target.value; update(v === "left" ? { x: 48 } : v === "center" ? { x: (PAGE_W - block.w) / 2 } : { x: PAGE_W - block.w - 48 }); }}><option value="">Aligner sur la page…</option><option value="left">À gauche</option><option value="center">Au centre</option><option value="right">À droite</option></select></label>
        <details className="precision-settings"><summary>Position et dimensions</summary><div className="inspector-two">{(["x", "y", "w", "h"] as const).map((k, n) => <label className="field" key={k}><span>{["Horizontal", "Vertical", "Largeur", "Hauteur"][n]}</span><input type="number" min={k === "w" || k === "h" ? 4 : 0} max={k === "x" || k === "w" ? PAGE_W : PAGE_H} value={Math.round(block[k])} onChange={e => { const value = Number(e.target.value); const patch = k === "x" ? { x: Math.max(0, Math.min(PAGE_W - block.w, value)) } : k === "y" ? { y: Math.max(0, Math.min(PAGE_H - block.h, value)) } : k === "w" ? { w: Math.max(4, Math.min(PAGE_W - block.x, value)) } : { h: Math.max(4, Math.min(PAGE_H - block.y, value)) }; update(patch); }} /></label>)}</div></details>
        <div className="layer-actions"><button onClick={() => replace({ ...model, blocks: [...model.blocks.filter(b => b.id !== block.id), block] })}>Au premier plan</button><button onClick={() => replace({ ...model, blocks: [block, ...model.blocks.filter(b => b.id !== block.id)] })}>À l’arrière-plan</button></div>
        </details>{!["text", "image", "table", "rule", "signature"].includes(block.kind) && <div className="bound-block-note"><Check size={15} /><p>Ce bloc reçoit automatiquement les informations de chaque nouvelle facture.</p></div>}
      </> : <div className="inspector-empty"><MousePointer2 size={27} /><h3>Un clic pour modifier.</h3><p>Choisissez un élément sur la page pour changer son texte, son style ou ses dimensions.</p></div>}
      <details className="model-manage"><summary>Gérer ce modèle</summary><button onClick={() => { const copy = { ...structuredClone(model), id: crypto.randomUUID(), name: model.name + " · copie" }; onChange([...models, copy]); open(copy.id); }}><Copy size={14} /> Copier le modèle</button><button onClick={() => { if (!confirm(`Supprimer le modèle « ${model.name} » ? Les factures déjà émises seront conservées.`)) return; const next = models.filter(m => m.id !== model.id); if (!next.length) next.push(createModel("reference")); onChange(next); if (activeId === model.id) onActive(next[0].id); setEditing(null); }}><Trash2 size={14} /> Supprimer le modèle</button></details></aside>}
    </div>{message && <div className="studio-message" role="status">{message}<button onClick={() => setMessage("")} aria-label="Fermer"><X size={15} /></button></div>}
  </div>;
}
