import { CircleHelp } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogTrigger } from "@/components/ui/dialog";

const guides: Record<string, { title: string; steps: [string, string][] }> = {
  factures: { title: "Factures & avoirs", steps: [["Créer", "Cliquez sur « Nouvelle facture », choisissez le client et ajoutez les prestations."], ["Consulter ou encaisser", "Sélectionnez une facture pour voir ses détails. La flèche ouvre le document ; « Enregistrer un paiement » met à jour son solde."], ["Changer de période", "Choisissez le mois en haut. « Clôturer ce mois » ferme la période et ouvre la suivante. L’onglet Avoirs réunit les corrections de factures."]] },
  creation: { title: "Créer une facture", steps: [["Client", "Choisissez un client enregistré. Ses coordonnées sont reprises automatiquement."], ["Prestations", "Saisissez la désignation, la quantité et le prix. Ajoutez une ligne pour chaque prestation ; contrat et destination sont facultatifs."], ["Émission", "Renseignez la TVA et l’avance reçue, puis vérifiez le total. « Émettre la facture » attribue son numéro et ouvre le document imprimable."]] },
  clients: { title: "Clients & paiements", steps: [["Choisir un client", "Ouvrez son compte pour retrouver toutes ses factures, même celles des mois clôturés."], ["Recevoir un paiement", "Cliquez sur « Enregistrer un paiement ». Choisissez la facture, le montant et le mode de paiement."], ["Suivre le solde", "Le reste à payer et les statuts se recalculent. Les versements restent dans l’historique ; une saisie erronée peut être annulée."]] },
  modele: { title: "Format de facture", steps: [["Bannière", "Importez l’image d’en-tête utilisée par votre entreprise."], ["Pied de page", "Saisissez votre texte ou utilisez une image. Une image remplace le texte."], ["Aperçu", "Utilisez +, − ou Agrandir pour lire le document. Les changements sont enregistrés automatiquement et concernent les prochaines factures."]] },
  entreprise: { title: "Réglages", steps: [["Coordonnées", "Renseignez les informations de l’entreprise. Elles apparaissent sur les prochaines factures."], ["Sauvegarde", "« Sauvegarder mes données » télécharge vos clients, factures, paiements et avoirs dans un fichier."], ["Restauration", "Choisissez une sauvegarde pour retrouver ses données. La démonstration conserve les informations dans ce navigateur."]] },
  apercu: { title: "Consulter une facture", steps: [["Imprimer", "« Imprimer / PDF » ouvre l’impression et permet d’enregistrer un PDF."], ["Encaisser", "« Enregistrer un paiement » met à jour le solde du client. Le document original reste inchangé."], ["Corriger", "« Créer un avoir » réduit le montant facturé et conserve un document lié à la facture d’origine."]] },
  avoir: { title: "Consulter un avoir", steps: [["Origine", "« Voir la facture d’origine » ouvre le document concerné."], ["Compte client", "L’avoir réduit le montant facturé. Le compte client affiche le nouveau solde."], ["Imprimer", "Utilisez « Imprimer / PDF » pour imprimer ou enregistrer ce document."]] },
};
export default function WorkspaceHelp({ view }: { view: string }) {
  const guide = guides[view === "suivi" ? "clients" : view] ?? guides.factures;
  return <Dialog><DialogTrigger asChild><button className="workspace-help-button"><CircleHelp size={15} /> Aide</button></DialogTrigger><DialogContent className="workspace-help-dialog"><DialogHeader><DialogTitle>{guide.title}</DialogTitle><DialogDescription>Les gestes essentiels.</DialogDescription></DialogHeader><ol className="workspace-help-steps">{guide.steps.map(([title, text], i) => <li key={title}><span>{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></DialogContent></Dialog>;
}
